### ISSUE TITLE
Chromium not found with 4.1.0 Beta

### ISSUE THREAD

**Issue by Martii** [bleachbit/bleachbit#1005]
> Decided to try the beta today and got something like this with current, well used, browser profiles I have and K/Ubuntu 20.x

> Chromium Version 85.0.4183.83 (Official Build) snap <- ICK! (64-bit):
> Also not picking up on my Chromium browser installation like prior versions on older Plasma/distro.

Installed via `sudo apt install chromium-browser`. No additional PPA's and is distro defaulted.

---

Here's a window snapshot:

<a href="https://user-images.githubusercontent.com/114709/92041155-f4d67880-ed34-11ea-8e09-a20a7339fdfa.jpg"><img src="https://user-images.githubusercontent.com/114709/92041155-f4d67880-ed34-11ea-8e09-a20a7339fdfa.jpg" alt="BleachBit 4 1 0 beta Main Titles" title="Click to enlarge... BleachBit 4 1 0 beta Main Titles" width="80" height="64"></a>

**Comment by az0** [comment]
The apt-get command installs the snap, and the the fix is a two-line change to chromium.xml to find the snap location . Here are some ways you can try it

1. Edit the file yourself
2. Download the whole file from GitHub and replace it
3. Check out the latest code (the whole repository) from GitHub
4. Wait for the next beta/stable release, which includes a .deb package

**Comment by Martii** [comment]
Chose option 1 for now. Seems to be working well. Thank you very much. :smile_cat:

**Comment by az0** [comment]
The fix released was released in [BleachBit 4.1.1 beta](https://www.bleachbit.org/news/bleachbit-411-beta) with deb installer packages
