### ISSUE TITLE
Ubuntu 20.04 installation reports syntax error in line 260

### ISSUE THREAD

**Issue by Sparxva** [bleachbit/bleachbit#1057]
Yesterday I installed bleachbit in Ubuntu 20.04 and noticed a syntax error reported in the python code.  Rather than include all of the text which passed by normally I will include only the relevant part:

Setting up bleachbit (3.9.0-1) ...
/usr/share/bleachbit/bleachbit/__init__.py:260: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if msgctxt **is not** None and msgctxt **is not** "":
Processing triggers for mime-support (3.64ubuntu1) ...

It just appears to be a syntax error in line 260 where someone used "is not" where the correct syntax is "!=" instead.  I don't know Python and can't help much, but it looks like a simple fix.

- Michael

**Comment by az0** [comment]
This looks like the issue #902 fixed in April. The BleachBit version in the Ubuntu repository is often old because of Ubuntu's "no rolling release" policy: they don't update BleachBit except for new versions of Ubuntu, so I provide new packages on the bleachbit.org site. Please update to the latest version [4.1.1 beta](https://www.bleachbit.org/news/bleachbit-411-beta).

**Comment by Sparxva** [comment]
Sorry, I did search first, but when I searched I think the search was
restricted to open issues and it did not come up.

Thanks, Mike
