### ISSUE TITLE
BleachBit 4.2.0 upgrade: Connection Error identified as Virus?

### ISSUE THREAD

**Issue by Saul-Goodnow** [bleachbit/bleachbit#1085]
Hello,
Just upgraded to BleachBit v. 4.2.0 on PC running Windows 10 Pro OS with McAfee Live Safe Anti-virus/Firewall.

- BleachBit version 4.2.0
- Build number 1795
- GTK version 3.18.9
- SQLite version 3.34.0

Opened BleachBit and received error message:  
`Error when opening a network connection to check for updates. Please verify the network is working and that a firewall is not blocking this application. Error message: <urlopen error unknown url type: https>`

Checked McAfee log which lists a threat in the BleachBit program:

> Virus or threat found
> Status:  Quarantined
> Scan type:  Real-time
> 
> We found one or several threats on your PC.
> Threat name:  Suspect!68475ff55e4a
> File:  C:\Program Files (x86)\BleachBit\_ssl.pyd

[![Image of BB_McAfeeError_20210105](https://raw.githubusercontent.com/Saul-Goodnow/IMAGES/main/BB_McAfeeError_20210105.JPG)](url)

Please advise if this finding is accurate or can be ignored.

With thanks and kind regards,
Kerrie

**Comment by az0** [comment]
@Saul-Goodnow 
Kerrie, if downloaded BleachBit from the official site www.bleachbit.org and it it is digitally signed by [Andrew Ziem](https://docs.bleachbit.org/doc/install-on-windows.html), then you have the original file. I believe this is safe and good to use.

As @m0lz  pointed out,t he installer is clean, but when I submitted one file (shown in @Saul-Goodnow 's screenshot), it came back with six false positives, so I created a separate ticket to track them: https://github.com/bleachbit/bleachbit/issues/1092 . This file has had false positives before because it's used to establish secure network connections, and this is generally a red flag for antivirus software. In our case, it's just used to check for software updates and download cleaner definitions. I'll work with the antivirus vendors for whitelisting.

**Comment by az0** [comment]
@Saul-Goodnow 

After noticing it was two days old, I refreshed the report for _ssl.pyd from VirusTotal, and now McAfee doesn't detect the false positive anymore, so please try again. Let em know how it goes

**Comment by az0** [comment]
@Saul-Goodnow 

McAfee responded that they whitelisted the _ssl.pyd file, and I confirmed it with a scan on VirusTotal. Please update your antivirus database, try again, and write a commend here to let me know how it goes.

**Comment by Saul-Goodnow** [comment]
> 
> 
> @Saul-Goodnow
> 
> McAfee responded that they whitelisted the _ssl.pyd file, and I confirmed it with a scan on VirusTotal. Please update your antivirus database, try again, and write a commend here to let me know how it goes.

@az0 -- Thank you very much for your assistance.  BleachBit 4.2.0 is running flawlessly.  Best, Kerrie
