### ISSUE TITLE
v4.2.0 tarballs from Sourceforge and GitHub are not the same

### ISSUE THREAD

**Issue by audreytoskin** [bleachbit/bleachbit#1088]
For BleachBit 4.2.0, the [Sourceforge tarball](https://sourceforge.net/projects/bleachbit/files/bleachbit/4.2.0/bleachbit-4.2.0.tar.gz/download) and [GitHub tarball](https://github.com/bleachbit/bleachbit/archive/v4.2.0.tar.gz) have different contents.

In particular, under the `doc/` directory, the Sourceforge version is missing `CODE_OF_CONDUCT.md` and `CONTRIBUTING.md`, although there might be other differences.

Just using the GitHub source might be more convenient, but Sourceforge has the signed checksums and stuff for verifying the downloads. And I would prefer to use the verifiable downloads while repackaging BleachBit.

**Comment by az0** [comment]
The tarballs on SourceForge  and download.bleachbit.org are the official versions. They are produced through the same process involving Python sdist, while GitHub automatically packages files directly from the repository. GitHub won't let me delete or modify these files. I prefer not to publish to a third place (GitHub), but for now I pushed the official LZMA tarball to GitHub.

So can you use just use SourcForge?

**Comment by terrycloth** [comment]
It doesn't really matter to me where the source archive comes from. It's just when I noticed that the discrepancy, I was confused about which source is more correct. I'm suddenly not sure, but I'd assumed that official source code releases and archives of the whole repository were generally the same.

...I suppose `doc/CONTRIBUTING.md` is (obviously) documentation about _contributing_ to, rather than _using_, BleachBit -- so maybe you're right to leave it out of the more "official" release. On the other hand, it looks like `CONTRIBUTING.md` [does get packaged in the RPM release](https://github.com/bleachbit/bleachbit/blob/d929e94d7dccf57eded6125f11ddaf78903b200f/bleachbit.spec#L171). :woman_shrugging:

**Comment by az0** [comment]
> official source code releases and archives of the whole repository were generally the same.

There are a few reasons for the difference. One is that the packaging process (involving Python sdist) was designed when GitHub was in its infancy and BleachBit was mostly hosted on SourcForge. Another is the sdist system does it "better", such as by producing an lzma archive that is smaller.

> ...I suppose `doc/CONTRIBUTING.md` is (obviously) documentation about _contributing_ to, rather than _using_, BleachBit -- so maybe you're right to leave it out of the more official release for users interested in building the application. On the other hand, it looks like `CONTRIBUTING.md` [does get packaged in the RPM release](https://github.com/bleachbit/bleachbit/blob/d929e94d7dccf57eded6125f11ddaf78903b200f/bleachbit.spec#L171).

You're right it doesn't need to be packaged, so I just removed it. Thanks
