### ISSUE TITLE
Clean function not working on Internet Explorer

### ISSUE THREAD

**Issue by banaagravrommel** [bleachbit/bleachbit#1178]
**Describe the bug**
The function does not work properly on Internet Explorer, upon cleaning everything the history and bookmark were not deleted. 

**To Reproduce**
1. Open the application
2. Select checkbox beside Internet Explorer
3. Click the clean button

The error happens every time.

**Expected behavior**
It should properly clean the data for Internet Explorer

**Screenshots**
http://recordit.co/CdJihiltI7

**Desktop**
 - OS: Windows 10
 - BleachBit version 4.3.0

**Additional context**
Sometimes it does not show that the data was not clean in the UI but sometimes it shows it was cleaned but the output is still nothing was cleaned

**Comment by az0** [comment]
Screen recording is helpful. Thank you again for that.

This issue is invalid because of the mismatch: in BleachBit, the browser Internet Explorer was cleaned (as you reported), but then the browser you opened afterwards was Microsoft Edge. There is a separate cleaner for Edge. 

One way to start MSIE, is to run the command `iexplore.exe` from the Windows run dialog.
