### ISSUE TITLE
Clean function does not work on Brave Browser

### ISSUE THREAD

**Issue by banaagravrommel** [bleachbit/bleachbit#1194]
**Describe the bug**
The clean function does not work on Brave Browser, it does not clean anything on the application

**To Reproduce**

1. Open the application
2. Select checkbox beside Brave Browser
3. Click clean button

The error happens every time.

**Expected behavior**
The function should work properly and should clean any data selected on the application.

**Screenshots**
http://recordit.co/t3XbETzKpy

**Desktop**

- OS: Windows 10
- BleachBit version 4.3.0

**Additional context**

**Comment by az0** [comment]
@banaagravrommel 
Do you use the normal stable release of Brave? Or Brave beta?

**Comment by banaagravrommel** [comment]
I did use the stable release.

**Comment by az0** [comment]
Thank you. I assigned to milestone 4.4 to work on this soon

**Comment by az0** [comment]
With Git revision 10ecc2a3c35bfb7a2cff42e5882e542c7c10afcd on Ubuntu 20.10, it cleans Brave 1.26.67 .

**Comment by az0** [comment]
I tested with Brave 1.26.67 on Windows 10 and BleachBit 4.3.0 beta. The first time I tried to clean, Brave was running in the background, so I had to kill the process. (Maybe I didn't wait long enough for it close naturally.) Afterwards, BleachBit cleaned it, and the history was gone when viewing it (CTRL+H).

@banaagravrommel 
In your screen recording, facebook.com shows in the autocomplete because it's bookmarked as shown in the bookmark bar. It is intentional to not clean bookmarks. A common test for cleaning history is to visit a site that is not bookmarked in the browser (Brave), close the browser, clean it, reopen the browser, and press CTRL+H to view the history page.

As another quick test, I disabled Brave shield, visited https://samy.pl/evercookie/, created an evercookie, noted the ID, closed the browser, cleaned it with BleachBit, started Brave, disabled the shield again, visited the evercookie page again, and noted it could not restore the ID.

Evercookie is older technology, so I did a similar test with https://demo.supercookie.me/ , and it created a different ID after cleaning, so this was good too.

One problem is that Brave remembers the last opened tab.
