### ISSUE TITLE
Garbled text when used in Japanese.

### ISSUE THREAD

**Issue by User9013** [bleachbit/bleachbit#1230]
As the title says, when I use it in Japanese, the text is garbled.
It seems that there is something wrong with the "fonts.conf" file, and if you replace this file with the v4.2 one, the garbled characters will disappear.
Thank you very much for your help.

**Comment by az0** [comment]
Sorry, about this problem: this problem was an unintended side effect of a performance enhancement.

You are clever to have come up with that workaround. Please see the [known issues ](https://www.bleachbit.org/news/bleachbit-440#known_issues) in the release notes for some other workarounds, in case you want to try another. I hope soon there will be a seamless solution in place.

If you are okay to testing it when it is ready, I will let you know through this issue ticket.

**Comment by az0** [comment]
@User9013 
I made a fix for Simplified Chinese, Traditional Chinese, and Japanese for BleachBit whether installed or in portable mode. Would you please be willing to test? The instructions are here: https://github.com/bleachbit/bleachbit/issues/1207#issuecomment-883870262

After testing, please reply in your original issue here (#1230) with information on whether it helped, and let me know which language you use.

**Comment by User9013** [comment]
After installing the test build, I copied "msyh.ttc" and "msyhbd.ttc" into "\share\fonts" and launched the application.
The garbled characters are gone!

**Comment by User9013** [comment]
The language used is "Japanese".
![無題](https://user-images.githubusercontent.com/65251154/126480124-d498fcfe-fc7e-4c82-89a4-b5e0cc87ff47.png)

**Comment by az0** [comment]
[Builds](https://ci.bleachbit.org/) since 4.4.1.2125 have reverted a startup performance improvement, so users of all languages will not experience the problem where text is shown as boxes. Now this issue is fixed. Thank you for reporting the problem and testing as changes were made.
