### ISSUE TITLE
[X] closes the program WITHOUT a security message

### ISSUE THREAD

**Issue by nico92GitHub** [bleachbit/bleachbit#1269]
Hello,
I'm surprised to see that during the cleanup, I can close BleachBit with the cross in the upper right corner and that there is no message asking me to confirm my choice to stop the cleanup and exit.
I look forward to hearing your views,
best regards,
Nico

**Comment by rados** [comment]
We can have a setting that turns that on/off.

**Comment by nico92GitHub** [comment]
Ha, thank you for your answer.
Will you add this setting in the next version?

regards,
Nico



We can have a setting that turns that on/off.

**Comment by az0** [comment]
The "are you sure you want to close" confirmation found in applications such as word processors prevents data loss, but here closing the application prevents data loss. Here the user can easily resume the cleaning process because the application remembers the previous settings, so reopening application is just a tiny inconvenience. 

Therefore adding a confirmation has little value. I would like to close this issue unless many users feel otherwise. If anyone else does, please add a comment and/or upvote the first comment in this thread using the GitHub "like" feature.

**Comment by nico92GitHub** [comment]
Thank you for your detailed answer.

I preferred to tell you this situation, because I thought it could generate errors during file deletions.
But obviously, you manage this premature exit.

regards,
Nico




The "are you sure you want to close" confirmation found in applications such as word processors prevents data loss, but here closing the application prevents data loss. Here the user can easily resume the cleaning process because the application remembers the previous settings, so reopening application is just a tiny inconvenience. 

Therefore adding a confirmation has little value. I would like to close this issue unless many users feel otherwise. If anyone else does, please add a comment and/or upvote the first comment in this thread using the GitHub "like" feature.

**Comment by az0** [comment]
When closing by "X'ing out the window," the application will safely shut down.
