### ISSUE TITLE
Replace Distro-Specific Installers For Linux With Universal Package Formats

### ISSUE THREAD

**Issue by ProfessorCode212** [bleachbit/bleachbit#1275]
Flatpaks, AppImages and Snaps are gaining a lot of popularity among most distros. Right now, BleachBit has way too many installers for Linux. It would be great if those could be replaced with one or more of the former package formats. It would make it much simpler for users to have one (or two) standardized way(s) of installing BleachBit on Linux and two of those three formats provide easy package management, which means users can have the latest version of BleachBit on their system. It would also reduce the burden on the development team while also making it available on most distros. Since Flatpak support is already on the way (#632), we are almost halfway there already.

**Comment by az0** [comment]
This was previously discussed here https://github.com/bleachbit/bleachbit/issues/342 , but I am open to reevaluating now. The next step is to better understand the how these formats compare, what would be required, etc.

**Comment by eadmaster** [comment]
+1 for appimages, also requested here:
https://github.com/bleachbit/bleachbit/issues/435

**Comment by jeroen7s** [comment]
Appimage or flatpak would be nice, I'm trying to use this on my Steam Deck, which has a readonly root.
So applications need to be portable in some way (like AppImage) or use flatpak to install

**Comment by az0** [comment]
Completed in https://github.com/bleachbit/bleachbit/issues/632

**Comment by ikabod** [comment]
In my opinion flatpak/snap are wrong formats, since they are not portable.

If you change your distro, you have to install the stuff again (or create your own repository which is unnecessary work, if using AppImages).

If you create an config folder for an AppImage, also the settings will be saved in the same drive, e. g. "BleachBit.AppImage" and "BleachBit.AppImage.config".

If you have this on a network drive or shared folder etc. you can run it on different distros without installing/configuring anything.

**Comment by az0** [comment]
[BleachBit version 6.0.1 beta](https://www.bleachbit.org/news/bleachbit-601-beta) was released with AppImage. When you have a chance, try it out. Thanks for your patience
