### ISSUE TITLE
Info for winapp2.ini

### ISSUE THREAD

**Issue by ghost** [bleachbit/bleachbit#1338]
Adding Description or some info to the cleaners imported from winapp2.ini would be great so that we will know what we are cleaning.

**Comment by az0** [comment]
BleachBit shows all the information in winapp2, which is much more limited than BleachBit's native CleanerML. This issue is out of scope because this project (BleachBit) neither maintains the[ community winapp2.ini file](https://github.com/MoscaDotTo/Winapp2) or sets the standard for the winapp2.ini format.
