### ISSUE TITLE
Bleachbit uninstall has bricked my Windows

### ISSUE THREAD

**Issue by Hughmungus669** [bleachbit/bleachbit#1353]
**Describe the bug**
After uninstalling Bleachbit using the built in uninstall tool in windows settings, the uninstall wizard took about 5 minutes going through all my files whilst it was uninstalling. After that I lost pretty much all of my programs as well as file explorer, internet access and the ability to searched or run any commands. Is there a way to restore all the files that were deleted? I am unable to back up to a previous save as I do not have one. I can’t even access the recycle bin because the directory is gone. Why is the bleach bit uninstall tied so heavily into windows operating files? And more importantly why did it delete them? There was no other programs or updates running at all at the time of install, it was the only thing currently going on my pc. It’s on the latest version of Windows 10, can’t tell you exactly what the version is
Please tell me there is a way to recover these files I am trying not to blow a fuse

**Comment by rados** [comment]
@Hughmungus669 This sounds like virus to me... I cannot imagine a way back... Re-installing the OS seems the only option...

**Comment by az0** [comment]
@Hughmungus669 

This is a frustrating situation. Of course, BleachBit's uninstaller should not be deleting any files except its own. To recover your files, you can do a general web search like "file recovery tool" or "undelete software." It helps to do it by booting from another disk or disk partition. There's a little more info in the BleachBit [FAQ: How do I recover a file deleted by BleachBit?  ](https://docs.bleachbit.org/doc/frequently-asked-questions.html), which was written for the application and not the uninstaller, so wiping and shredding to not apply.   Because this sounds like a non-reproducible situation, I am going to close the ticket.
