### ISSUE TITLE
Fullscreen glitch with 2265 Python 3.10 build using natively installed vcruntime140.dll

### ISSUE THREAD

**Issue by kenrap** [bleachbit/bleachbit#1410]
After experiencing the bug in #1409, closing and opening Bleachbit again would automatically go in a fullscreen mode without showing titlebar and covering the Windows taskbar. I couldn't get out of it using keyboard shortcuts to unmaximize or tile the window. I was able to close Bleachbit by hitting the Windows (super) key to reveal the taskbar and right click on the task to finally close it.

**Steps To reproduce the behavior**
1. Do the steps mentioned in #1409.
2. Close and open Bleachbit again.

**Expected behavior**
Should open in the usual floating-mode window and not be in fullscreen mode.

**Desktop Specs**
OS: Windows 11 (via qemu-kvm using virt-manager to manage passthrough configurations)
BleachBit 4.4.2.2265

**Additional context**
Deleting the `%APPDATA%\BleachBit\bleachbit.ini` file restores Bleachbit back to the state with the first bug in #1409 and therefore repeats this cycle.

**Comment by az0** [comment]
@kenrap 

Does this happen with the newer [build 2310](https://ci.bleachbit.org/?prefix=dl/4.4.2.2310-mkhon-python310/)?

**Comment by sanjaykaria** [comment]
> I couldn't get out of it using keyboard shortcuts to unmaximize or tile the window. I

@kenrap  You can use Alt+F4 to close Bleachbit in full screen mode (on Windows)

**Comment by sanjaykaria** [comment]
@az0 

I think this issue is related to the action of adding the 2 options "window_fullscreen" and  "window_maximized", to fix #204.  Somehow, the option window_fullscreen is getting set and the "fullscreen glitch" which is basically BB in fullscreen mode occurs.

There is an option(icon on right-top) to maximize BleachBit on the GUI, but there is no option to make it FullScreen( at least I am not aware of it ) on the GUI. Also, I think the fullscreen option is not needed, only the maximize window should suffice.

So, if we remove the "window_fullscreen" option and just use "window_maximized", it should suffice to store the window size and position.

**Comment by az0** [comment]
@sanjaykaria 

Yes, I do not see a way to make the application go full screen, so remove the code related to it.

**Comment by az0** [comment]
_Administrative note_

I am splitting apart milestones 4.6 and 5.0 where 4.6 still has Python 3.4 and 5.0 has Python 3.10, which is not ready yet. This issue only exists with the newer Python 3.10 and newer GTK, so I left this issue targeted to the 5.0 milestone. The fix is in the master branch, so I left the PR targeted to the 4.6 milestone.
