### ISSUE TITLE
[Question] Is this project abandoned?

### ISSUE THREAD

**Issue by gracie95** [bleachbit/bleachbit#1478]
It's about a year since latest version released.

**Comment by az0** [comment]
A final release is "overdue," so thanks for your patience, but far from abandoned. Since the last stable release, there has been much development on multiple branches, and there has been activity on the issue tracker. If you are on Windows, you can easily grab the latest build  from https://ci.bleachbit.org/ , or if you are on Linux, Git is a good way to get the latest build.
