### ISSUE TITLE
Mircosoft Edge cannot be cleaned because it is running. Close this software, then try again.

### ISSUE THREAD

**Issue by nico92GitHub** [bleachbit/bleachbit#1498]
Hello
As you can see in my screenshot, I whitelisted 3 "edge" objects, but Bleachbit doesn't seem to take this whitelist into account.
![tilt_bleachbit_ms_edge](https://github.com/bleachbit/bleachbit/assets/22394276/7367c088-1b48-4f18-8f37-1743eb39a588)
The error line indicates a generic name for the process in question. Can you help me find the name of the program to whitelist?
Awaiting your return,
Nicolas

**Comment by geo711** [comment]
I was given the solution to this issue. Open the settings in Microsoft Edge and scroll down to "system and performance" and then toggle "Startup boost" off. Restart your computer and the issue should be resolved. I do not use Edge as my default browser and was not aware of this setting being on. I use Firefox as my browser. Hope this helps.

**Comment by nico92GitHub** [comment]
Thank you for this solution which I would not have thought of. Because like you I don't use edge but Firefox also.


Nico




I was given the solution to this issue. Open the settings in Microsoft Edge and scroll down to "system and performance" and then toggle "Startup boost" off. Restart your computer and the issue should be resolved. I do not use Edge as my default browser and was not aware of this setting being on. I use Firefox as my browser. Hope this helps.

**Comment by az0** [comment]
Thank for posting the solution, @geo711  .

As you may have figured out, the [Edge Startup Boost](https://techcommunity.microsoft.com/t5/articles/startup-boost-faq/m-p/1810423) is a feature to run the browsers always in the background, so it feels faster to start when you want to use it. It's already warmed up because it was already running.

As there is a solution to disable Startup Boost, I will close this ticket.

**Comment by az0** [comment]
If anyone else comes across this old issue ticket, I added a YouTube video: ["BleachBit: browser cannot be cleaned because it's running"](https://www.youtube.com/watch?v=xvOTn2ING3w) with instructions for Microsoft Edge on Windows.

Also, I want in the future to add an option to automatically kill Edge.
