### ISSUE TITLE
bug:  msvcr100.dll is missing

### ISSUE THREAD

**Issue by diogeneswasok** [bleachbit/bleachbit#1569]
Trying to install 4.5.1.2523 on windows 10 64 bit . I get a message msvcr100.dll is missing when I try to run it. I have installed vcrdist_64.exe which is a suggested fix but to no avail.

**Comment by az0** [comment]
Are you a first time user?

Did this happen with versions 4.4.2 stable or 4.5.0 beta?

**Comment by rados** [comment]
You may try with vcrdist_x86.exe - the 32 bit version.

**Comment by diogeneswasok** [comment]
4.5.0 works fine.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by diogeneswasok** [comment]
Sorry 4.4.2 is fine. The issue is only with 4.5.2 beta

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rados** [comment]
I just installed BleachBit-4.5.1.2523-setup.exe and there were no problems. Will try to reproduce your situation.

**Comment by rados** [comment]
I could reproduce it by renaming my msvcr100 in sysWOW64 folder. Then I downloaded and installed vcredist_x86.exe and this fixed the problem

**Comment by az0** [comment]
> Sorry 4.4.2 is fine. The issue is only with 4.5.2 beta 

That is strange because 4.4.2, 4.5.0, and 4.5.1 all use the same basic low-level components, so it should be all or none.

Have you tried with vcrdist_x86.exe  (as Rados suggested)?

**Comment by diogeneswasok** [comment]
I have downloaded vcredist_x86.exe and the problem persists. Version 4.4.2 still loads and runs OK. After running vcredist_x86.exe, there is no msvcr100.dll in my SysWOW64 folder. There is, however, a msvcr100_clr400.dll?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by diogeneswasok** [comment]
I have since downloaded both vcredist_x86.exe and vcredist_x64.exe from an alternative web source and msvcr100.dll is now in my SysWOW64 folder and 4.5.2 beta now loads and runs without errors. Thanks for your help.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by danield72** [comment]
I just downloaded the RTM (?) version (4.6.0.2537) and I'm running into the same issue - MSVCR100.DLL is reported as missing during the installation - and when subsequently attempting to run what got installed.

I'm on a relatively clean version of Windows 10 22H2, installed back in June (not an upgrade), and I don't believe I've had to install the VC++ runtime since setting up the OS.  I don't have MSVCR100.DLL existing anywhere, and I've tried multiple versions of VC_REDIST.X86.EXE (the 32-bit version) from https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170.  None (!) of them seem to set up MSVCR100.DLL anywhere.

Strictly speaking, since this is built with Python, the problem really is with Python rather than BleachBit, so I'll try to determine exactly what version of the runtime is needed by Python.  I'm not a Python developer, but I'm assuming this is built with the latest version...I'll post a follow-up if I find a solution...

**Comment by az0** [comment]
>but I'm assuming this is built with the latest version...I'll post a follow-up if I find a solution...

BleachBit 4.6.0 uses Python 3.4.4, which is old. 

There is a development branch for Python 3.10, but it's not ready.

**Comment by danield72** [comment]
A separate discussion on StackOverflow (https://stackoverflow.com/questions/20092983/version-of-msvcrxx-dll-that-my-python-interpereter-compiles-with) led me to the runtime for VC2010 With SP1, which I happened to have in my personal archive.  The URL I had saved along with it is http://www.microsoft.com/en-us/download/confirmation.aspx?id=8328 but that's unfortunately dead.

I ran the installer I already had (vcredist_x86.exe); the SHA-256 hash I have is 66B797B3B4F99488F53C2B676610DFE9868984C779536891A8D8F73EE214BC4B.  **This fixed the problem** and BleachBit 4.6 now runs.

The page I linked to in my previous message (learn.microsoft.com[...]) has a link to the VC2010 With SP1 runtime, although that version is labeled 10.0.40219.325.  My installer EXE's Product Version is shown as 10.0.40219.01, but I suspect the one from the MS page *should* work as well (and is probably the preferable version over the one I have).

Make of this information what you will.

**Comment by az0** [comment]
> I have since downloaded both vcredist_x86.exe and vcredist_x64.exe from an alternative web source and msvcr100.dll is now in my SysWOW64 folder and 4.5.2 beta now loads and runs without errors. Thanks for your help. Sent from Outlook for Android

@diogeneswasok 

Do you still have the URL where you got these?

>I ran the installer I already had (vcredist_x86.exe); the SHA-256 hash I have is 66B797B3B4F99488F53C2B676610DFE9868984C779536891A8D8F73EE214BC4B. This fixed the problem and BleachBit 4.6 now runs.

@danield72 

This level of detail is helpful. Thank you.

Did you have this problem with the previous stable version BleachBit 4.4.2?


.....

I am looking for the root cause. The [screenshot ](https://github.com/bleachbit/bleachbit/issues/1575#issuecomment-1794420067) shows fc-cache executing. This was added in commit 14bd69e214c23a585be70576f9c648474e255ec9, which was included in BleachBit version 4.4.2, but diogeneswasok and other users indicated or implied that 4.4.2 worked fine.

The `appveyor.xml` file has multiple changes since 4.4.2 for SQLite (very unlikely related), UPX, and plyer. These do not stand out as a likely explaination.

The fc-cache.exe in BleachBit 4.4.2 and 4.6.0 (portable) have identical hashes, so it did not change since 4.4.2.

BleachBit 4.6.0 uses NSIS 3.03 released in 2018, so the NSIS version also seems to not explain the issue.

The same issue is reported here: https://github.com/bleachbit/bleachbit/issues/1575 , so there's more info there

**Comment by az0** [comment]
The root cause cause looks like this commit https://github.com/bleachbit/bleachbit/commit/f0a8f2faf2674ce64e3a12cb90c74cd4d2d652b0 , which was part of the effort to upgrade Python 3.4 to 3.10

**Comment by danield72** [comment]
> @danield72
> 
> This level of detail is helpful. Thank you.
> 
> Did you have this problem with the previous stable version BleachBit 4.4.2?

I never installed previous versions of BleachBit on this system; as mentioned, the machine got a clean OS install back in June and I haven't had any application need the VC runtime until I tried (for the first time since the OS install) this latest version of BleachBit.

But if I would've run into the same error with previous installs, I would've made a note of it in my archive folder, and I have none.  Although it's entirely possible I already *had* something that required me to install the runtime on a previous machine, which would've hidden the problem.  Sorry I can't help you there.

**Comment by JimboUS** [comment]
Error was:
Code execution cannot proceed because msvcr100.dll was not found.

For the below known error all that's required is to copy mcvcr100.dll from the SysWOW64 folder of another Win 11 computer to the computer's SysWOW64 folder that was getting the Bleachbit error as that file was missing in that folder.
The mcvcr100.dll file was present in the system32 folder, it was not missing as it was in the SysWOW64 folder.
See below for more details.

KNOWN ERROR:

When installing on Windows, users may see the error "Code execution cannot proceed because msvcr100.dll was not found." This happens during the font cache initialization, and the installer will show that fc-cache.exe is running. Your options include (1) installing the 32-bit Microsoft Visual C++ redistributable runtime or (2) [downgrading](https://sourceforge.net/projects/bleachbit/files/bleachbit/4.4.2/) to BleachBit 4.4.2.

If you have this msvcr100 error, please consider [filing an issue](https://github.com/bleachbit/bleachbit/issues/new/choose) to provide more information for troubleshooting. Include this info:

Your version of Windows:  Win 11 latest update on both PCs.

Whether you are upgrading from an old version of BleachBit:  Upgraded from previous version.

If you are upgrading, the previous version of BleachBit and whether it had this error:  Never had that or any other error before the latest Bleachbit update.

A screenshot of the error [like this one](https://user-images.githubusercontent.com/127061417/280658766-b2c671de-9ae7-44e9-9ed0-83ff064a29fa.png), or indicate whether it indicates that fc-cache.exe is executing.

Whether the error was resolved by installing [Visual Studio 2010 (VC++ 10.0) SP1 x86](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe)
Did NOT attempt the above as the issue was resolved as stated above.

**Comment by JimboUS** [comment]
It's NOT necessary to install Visual Studio 2010 IF you follow my post above.
Check both the system32 folder and the SysWOW64 folder for the missing mcvcr100.dll file and just copy it over IF it's missing.
ONLY install Visual Studio IF the issue is not resolved by the simple copying of the file.

Here it is again:

For the below known error all that's required is to copy mcvcr100.dll from the SysWOW64 folder of another Win 11 computer to the computer's SysWOW64 folder that was getting the Bleachbit error as that file was missing in that folder.
The mcvcr100.dll file was present in the system32 folder, it was not missing as it was in the SysWOW64 folder.

**Comment by danield72** [comment]
> It's NOT necessary to install Visual Studio 2010 IF you follow my post above. Check both the system32 folder and the SysWOW64 folder for the missing mcvcr100.dll file and just copy it over IF it's missing. ONLY install Visual Studio IF the issue is not resolved by the simple copying of the file.

Just so we're clear, I don't think anyone was suggesting to install *Visual Studio 2010* - only the *runtime* for it.  One's a developer tool and needs gigabytes; the other is intended to be installed by end users and is just a few MBs.  That is the *supported* method of getting system DLLs installed on Windows.

Otherwise - it may work - but it's a hack.  If msvcr100.dll itself has dependencies, installing the runtime will ensure all of its required files are present.  But if you're just copying the one DLL over, then you'll have to repeat the investigation if msvcr100.dll itself needs an additional file you don't happen to already have.  Why not just do it the "official" way?

As a bonus, you get a proper uninstaller for the runtime as well.  If you later install something else that requires the same DLL, but you're not aware of that, you'll break that other program if you just blindly delete the DLL.  Whereas the (un)installer will do the proper reference count housekeeping, and warn you you're about to break something else.

**Comment by JimboUS** [comment]
Understood, and a great explanation.
But installing 14 year old programs in recent OSs with the latest updates/upgrades, carries certain unpredictabilities.
That's been my experience over the years, so I always try the simplest path first and then take it from there should issues arise.

I installed this latest Bleachbit version on several computers, older and newer, Win 10 and Win 11 all with the latest MS updates and the only PC that had this error issue is a very new HP laptop hardly used, with Win 11 Pro.
It had the previous Bleachbit version working with no problems.

Just a guess here, but it was very strange that the only file missing was the SysWOW64 folder mcvcr100.dll file, NOT the system32 file.  Is it possible that the REQUIRED uninstallation of the previous Bleachbit version also removed the SysWOW64 folder mcvcr100.dll file???
That's something for the Bleachbit developers to figure out.

**Comment by danield72** [comment]
Point taken, but I would also add that -- despite all the (mostly well-deserved) criticism it gets -- Microsoft generally goes out of its way to ensure older versions of their own software do not break on operating systems that did not yet exist at the time said software was written.  For something as important as the C++ runtime, I'd think even though this particular version is completely out of support, newer OSes can still recognize the installer and probably have a software shim, with all the tweaks necessary, to ensure it's not going to break.

That's the theory.  :-)  I called it a hack, but if copying the one file over works, I wouldn't hesitate to call it a valid solution.  You just have to trust your source for that DLL - I'd personally rather download from Microsoft's own site, and get an installer that has the proper Microsoft signature that can be validated.  Even though the DLL, as a standalone, is signed, most people wouldn't know to look for it, and could've been stripped out.  Whereas the installer will enforce the certificate validation.  There's too many web sites that offer single DLL downloads, whose origin might be of a dubious nature, and carry "a little extra" you didn't ask for.

Also to clarify - my system never had - and still doesn't have - a version of msvcr100.dll in its system32 folder - the 32-bit runtime installer only added it to SysWOW64 (and obviously that's what the 64-bit runtime installer would do).  Windows 10 22H2 (what I'm running) does NOT ship with msvcr100.dll in either folder - as mentioned, I never had BleachBit on it, so it's not like a previous version's uninstaller mistakenly removed the file.

As a developer, I use virtual machines extensively, and always have clean versions of Windows, so it's pretty easy to determine whether a given OS shipped with a specific file or not.

Anyway, I've enjoyed this discussion, and maybe we're straying too far from the discussion at hand :-) but I think right now we have a pretty solid understanding of what's going on, and you have 2 known solutions to offer users.  If that's not already on an FAQ somewhere, I suggest it gets added (I'd suggest telling users to get the file from another system they trust first, and if they can't locate a copy of it, then link to the "official" installer page from MS, rather than suggesting they find the one specific file from some random web site).

**Comment by az0** [comment]
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) which has the fix for the error "msvcr100.dll was not found."**  (A separate installation of the Microsoft Visual Studio runtime is no longer needed.) If you still see an issue with msvcr100.dll, reopen this issue.

While testing that, please also check that there are no issues with the digital certificate. When running the installer and running the application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.
