### ISSUE TITLE
v4.6.0 install problem: "code execution cannot proceed..."

### ISSUE THREAD

**Issue by box89car** [bleachbit/bleachbit#1575]
**Describe the bug**
After download, during install receive msg "The code execution cannot proceed...." and install fails. Recommends reinstall attempt but this also fails.

**To Reproduce**
1. Download
2. Double click downloaded file to install
3. Install begins but is interrupted by error msg

The error happens each time I try to install.  Have tried four times.

**Expected behavior**
Clean install, finish and start program.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - BleachBit version [4.6.0]

**Comment by az0** [comment]
Please include a screenshot showing the error and all active parts of the application.  You can attach it as a file using drag and drop. Also, if the image is in the clipboard, type CTRL+V in the comment box, and it will attach the photo.

Are there any steps between double clicking the downloaded file and the error happens. Are there any interactions in between, like any clicking or typing?

The file may have not downloaded properly. Delete the installer, and try downloading again, maybe using a different browser. You can also verify the download by calculating the checksum or [checking the digital signature](https://docs.bleachbit.org/doc/install-on-windows.html). When you start the installer, do you see the digital signature is valid?

Did previous versions of BleachBit install correctly, and if so, which versions?

**Comment by ebaldridge** [comment]
It needs an old redistributable that most won't have installed.
https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe

**Comment by TheNightRider12** [comment]
I am having this same issue when upgrading Bleachbit. Installing the redistributable from the above comment fixes the issue for me.

**Comment by box89car** [comment]
Andrew, Brandon’s screenshot is same as mine. I’m going to try the redistributable that others have mentioned.Thanks




On Monday, November 6, 2023, 12:02 PM, IamTheOne12 ***@***.***> wrote:




I am having this same issue when upgrading Bleachbit. Installing the redistributable from the above comment fixes the issue for me.

**Comment by box89car** [comment]
Happy to report the old redistributable worked for me as well. Thanks to all!

    On Monday, November 6, 2023 at 01:47:49 PM EST, Brandon Coutoulakis ***@***.***> wrote:  
 
 



It needs an old redistributable that most won't have installed. https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe


Interesting, this works for me as well ─ thanks!

Initially I had tried vcredist_x64.exe but that didn't work ─ wasn't too far off!

**Comment by az0** [comment]
Thank you all for this info. 

A few notes

* There is more info in another ticket with the same issue: https://github.com/bleachbit/bleachbit/issues/1569
* In the reports, I see both Windows 10 and 11, so it's not specific to either version of Windows.
* I also see that before this happened, you all had BleachBit version 4.4.2 (released November 2021) working. If you did not use 4.4.2, let me know.
* I called out this problem in the [BleachBit 4.6.0 release notes](https://www.bleachbit.org/news/bleachbit-460#known_issues)
* The linked vcredist_x86 is Visual Studio 2010 (VC++ 10.0) SP1 10.0.40219.325, and another user in the other issue ticket also had success with this.

**Comment by rater23** [comment]
went to dll.com and found the .dll then add it to program folder works now

**Comment by JimboUS** [comment]
Error was:
Code execution cannot proceed because msvcr100.dll was not found.

For the below known error all that's required is to copy mcvcr100.dll from the SysWOW64 folder of another Win 11 computer to the computer's SysWOW64 folder that was getting the Bleachbit error as that file was missing in that folder.
The mcvcr100.dll file was present in the system32 folder, it was not missing as it was in the SysWOW64 folder.
See below for more details.

KNOWN ERROR:

When installing on Windows, users may see the error "Code execution cannot proceed because msvcr100.dll was not found." This happens during the font cache initialization, and the installer will show that fc-cache.exe is running. Your options include (1) installing the 32-bit Microsoft Visual C++ redistributable runtime or (2) [downgrading](https://sourceforge.net/projects/bleachbit/files/bleachbit/4.4.2/) to BleachBit 4.4.2.

If you have this msvcr100 error, please consider [filing an issue](https://github.com/bleachbit/bleachbit/issues/new/choose) to provide more information for troubleshooting. Include this info:

Your version of Windows:  Win 11 latest update on both PCs.

Whether you are upgrading from an old version of BleachBit:  Upgraded from previous version.

If you are upgrading, the previous version of BleachBit and whether it had this error:  Never had that or any other error before the latest Bleachbit update.

A screenshot of the error [like this one](https://user-images.githubusercontent.com/127061417/280658766-b2c671de-9ae7-44e9-9ed0-83ff064a29fa.png), or indicate whether it indicates that fc-cache.exe is executing.

Whether the error was resolved by installing [Visual Studio 2010 (VC++ 10.0) SP1 x86](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe)
Did NOT attempt the above as the issue was resolved as stated above.

**Comment by MelisandeL** [comment]
Worked for me as well! Thank you so much! Happy New Year!

**Comment by az0** [comment]
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) which has the fix for the error "msvcr100.dll was not found."**  If you still see an issue with msvcr100.dll, reopen this issue.

While testing that, please also check that there are no issues with the digital certificate. When running the installer and running the application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.
