### ISSUE TITLE
MSVCR100.dll was not found

### ISSUE THREAD

**Issue by forapplicationonly** [bleachbit/bleachbit#1583]
I'm getting this error on 4.6.0.
![image](https://github.com/bleachbit/bleachbit/assets/63014562/e25d439a-74b1-402f-8590-91f19c6ee874)

I'm sure I finished installation. I uninstall/reinstall multiple times. I even tried the portable version but same result.
Older versions don't have that error so that's what I'm still using for now.

Windows 11 Home.

**Comment by JimboUS** [comment]
Error was:
Code execution cannot proceed because msvcr100.dll was not found.

For the below known error all that's required is to copy mcvcr100.dll from the SysWOW64 folder of another Win 11 computer to the computer's SysWOW64 folder that was getting the Bleachbit error as that file was missing in that folder.
The mcvcr100.dll file was present in the system32 folder, it was not missing as it was in the SysWOW64 folder.
See below for more details.

KNOWN ERROR:

When installing on Windows, users may see the error "Code execution cannot proceed because msvcr100.dll was not found." This happens during the font cache initialization, and the installer will show that fc-cache.exe is running. Your options include (1) installing the 32-bit Microsoft Visual C++ redistributable runtime or (2) [downgrading](https://sourceforge.net/projects/bleachbit/files/bleachbit/4.4.2/) to BleachBit 4.4.2.

If you have this msvcr100 error, please consider [filing an issue](https://github.com/bleachbit/bleachbit/issues/new/choose) to provide more information for troubleshooting. Include this info:

Your version of Windows:  Win 11 latest update on both PCs.

Whether you are upgrading from an old version of BleachBit:  Upgraded from previous version.

If you are upgrading, the previous version of BleachBit and whether it had this error:  Never had that or any other error before the latest Bleachbit update.

A screenshot of the error [like this one](https://user-images.githubusercontent.com/127061417/280658766-b2c671de-9ae7-44e9-9ed0-83ff064a29fa.png), or indicate whether it indicates that fc-cache.exe is executing.

Whether the error was resolved by installing [Visual Studio 2010 (VC++ 10.0) SP1 x86](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe)
Did NOT attempt the above as the issue was resolved as stated above.

**Comment by az0** [comment]
As JimboUS wrote, please try installing [Visual Studio 2010 (VC++ 10.0) SP1 x86](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe). Does this help?

**Comment by JimboUS** [comment]
It's NOT necessary to install Visual Studio 2010 IF you follow my post above.
Check both the system32 folder and the SysWOW64 folder for the missing mcvcr100.dll file and just copy it over IF it's missing.

Here it is again:

For the below known error all that's required is to copy mcvcr100.dll from the SysWOW64 folder of another Win 11 computer to the computer's SysWOW64 folder that was getting the Bleachbit error as that file was missing in that folder.
The mcvcr100.dll file was present in the system32 folder, it was not missing as it was in the SysWOW64 folder.
See below for more details.

**Comment by forapplicationonly** [comment]
> As JimboUS wrote, please try installing [Visual Studio 2010 (VC++ 10.0) SP1 x86](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe). Does this help?

Yes. Thanks to all who help

**Comment by Elmehdioub** [comment]
Thank you so much guys all those who said to install this [Visual Studio 2010 (VC++ 10.0) SP1 x86] really helped me a lot i was dealing with this problem tell I get frustrated and one and by the way for me when i tried to copy that missing DLL from another windows and when I did a different error accured it says something like that unstable with 0x000007b i dont remember the corect error spelling cause now i fixed the issue when i install the vc++ 2010 sp1 thank you.

**Comment by bcutter** [comment]
Latest BleachBit update broke this... was running totally fine before.

**Comment by Neurrone** [comment]
Installing the runtime didn't work for me, on Windows 11 fresh Bleachbit install.

I'm downgrading to a previous version for now.

**Comment by rados** [comment]
@Neurrone, you might verify if you installed the 32bit version, because the 64bit wouldn't help. Usually installing the 32 bit version fixes this problem. If not, probably there is something special on your machine...

**Comment by sawft99** [comment]
This resolved the dll issue for me. Outside this issue, but it did seem like the 'Bleachbit is starting screen' took longer than normal
