### ISSUE TITLE
MSVCR100.DLL Errorr with Bleach Bit 4.6

### ISSUE THREAD

**Issue by abear27** [bleachbit/bleachbit#1587]
Per the request on "Known Issues" published on the BleachBit site:

Your version of Windows:  23H2 (22631.2506)
Whether you are upgrading from an old version of BleachBit: The same error occurred with fc-cache in both scenarios.  I was upgrading, but went the upgrade failed I uninstalled the app and manually removed folders, then re-downlaoded and ran the installer fresh.
A screenshot of the error:  Same as the sample noted, and came up both in either case while fc-cache was executing.
Whether the error was resolved by installing [Visual Studio 2010 (VC++ 10.0) SP1 x86]:     Yes it was!

Hope this helps give some context on the number of people experiencing the issue.

**Comment by az0** [comment]
Thank you for the info!

**Comment by az0** [comment]
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) which has the fix for the error "msvcr100.dll was not found."**  (A separate installation of the Microsoft Visual Studio runtime is no longer needed.) If you still see an issue with msvcr100.dll, reopen this issue.

While testing that, please also check that there are no issues with the digital certificate. When running the installer, fc-cache.exe, and running the BleachBit application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.
