### ISSUE TITLE
Missing MSVCR.DLL 

### ISSUE THREAD

**Issue by Yrando** [bleachbit/bleachbit#1595]
when trying to download the portable version this file is missing

**Comment by az0** [comment]
See the MSVC runtime instructions in the known issues section of the [release notes](https://www.bleachbit.org/news/bleachbit-460). Does this help?

**Comment by Morse6690** [comment]
This worked for me.

**Comment by Yrando** [comment]
I have a low end pc is there a way to just copy the dll from a previous entry or without installing additional stuff

**Comment by az0** [comment]
> I have a low end pc is there a way to just copy the dll from a previous entry or without installing additional stuff

Copy `msvcr100.dll` from the portable zip file from [BleachBit 4.4.2](https://www.bleachbit.org/download/old) to the install directory of the new version. Put it in the same directory as `bleachbit.exe`.

I'm curious what you mean by low end. What is the disk capacity? Which version of Windows?

**Comment by Yrando** [comment]
That fixed the problem thank you very much for the quick response

Sorry i just don't want to install extra dependencies as i'm running windows on a small i5 laptop

**Comment by az0** [comment]
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) which has the fix for the error "msvcr100.dll was not found."**  (A separate installation of the Microsoft Visual Studio runtime is no longer needed.) If you still see an issue with msvcr100.dll, reopen this issue.

While testing that, please also check that there are no issues with the digital certificate. When running the installer and running the application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.
