### ISSUE TITLE
Unable to launch bleach it after the recent update

### ISSUE THREAD

**Issue by anees1221** [bleachbit/bleachbit#1599]
![bleach it](https://github.com/bleachbit/bleachbit/assets/20615418/1610f8ab-ae74-4c49-acd7-3dfe5672f5b2)

**Comment by az0** [comment]
See the known issues section of the [4.6.0 release notes](https://www.bleachbit.org/news/bleachbit-460). Does this help?

**Comment by PaulMcF1987** [comment]
I have updated to 4.6.0, and I am also having the same issue

**Comment by rados** [comment]
Have you installed [Visual Studio 2010 (VC++ 10.0) redistributable SP1 x86](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe) like mentioned in known issues section of the [4.6.0 release notes](https://www.bleachbit.org/news/bleachbit-460)?

**Comment by az0** [comment]
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) which has the fix for the error "msvcr100.dll was not found."**  (A separate installation of the Microsoft Visual Studio runtime is no longer needed.) If you still see an issue with msvcr100.dll, reopen this issue.

While testing that, please also check that there are no issues with the digital certificate. When running the installer and running the application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.
