### ISSUE TITLE
i have problem on install bleachbit

### ISSUE THREAD

**Issue by Yokido** [bleachbit/bleachbit#1607]
---------------------------
bleachbit.exe - System Error
---------------------------
The code execution cannot proceed because MSVCR100.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
anyone know how to fix

**Comment by az0** [comment]
See BleachBit 4.6.0 release notes: [known issues](https://www.bleachbit.org/news/bleachbit-460#known_issues).

**Comment by az0** [comment]
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) which has the fix for the error "msvcr100.dll was not found."**  (A separate installation of the Microsoft Visual Studio runtime is no longer needed.) If you still see an issue with msvcr100.dll, reopen this issue.

While testing that, please also check that there are no issues with the digital certificate. When running the installer and running the application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.
