### ISSUE TITLE
Remove Visual Studio 2010 (VC++ 10.0) redistributable SP1 requirement

### ISSUE THREAD

**Issue by pinhead88** [bleachbit/bleachbit#1608]
I understand that Windows installations may show the error "Code execution cannot proceed because msvcr100.dll was not found." if Visual Studio 2010 (VC++ 10.0) redistributable SP1 x86 is not installed.  Is it possible to remove the requirement for Visual Studio 2010 as it is no longer supported? ref: https://learn.microsoft.com/en-us/lifecycle/products/visual-studio-2010

Having Visual Studio 2010 (VC++ 10.0) installed triggers our compliance monitors to have it remove because its 2+ years out of support.

**Comment by az0** [comment]
Some options are

1. Downgrade to [4.4.2](https://www.bleachbit.org/download/old)
2. In 4.6.0, uninstall the MSVC2010, but copy over MSVC the DLL (like from BleachBit 4.4.2 portable) to the installation directory of 4.6.0
3. Use the[ 4.6.1 pre-release](https://ci.bleachbit.org/)
4. Wait for 4.6.1 beta or 4.6.2 stable

**Comment by az0** [comment]
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) which has the fix for the error "msvcr100.dll was not found."**  (A separate installation of the Microsoft Visual Studio runtime is no longer needed.) If you still see an issue with msvcr100.dll, reopen this issue.

While testing that, please also check that there are no issues with the digital certificate. When running the installer and running the application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.
