### ISSUE TITLE
 MSVCR100.dll error

### ISSUE THREAD

**Issue by lolinajdi** [bleachbit/bleachbit#1638]
When attempting to install BleachBit on my Windows 11 23H2 system, I encountered an error during the installation process. Despite initiating the installation procedure, an error message prevented the successful completion of the installation. This issue hindered the progress of installing BleachBit

![error](https://github.com/bleachbit/bleachbit/assets/65453926/c4dc2536-7158-4727-8ea4-2eaae1612818)

**Comment by az0** [comment]
Please see the[ known issues](https://www.bleachbit.org/news/bleachbit-460) in the 4.6.0 release notes. After installing [Visual Studio 2010 (VC++ 10.0) redistributable SP1 x86](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe). how does it work?

**Comment by killdashnine420** [comment]
I've had this issue occur on multiple machines as well. I'll try your trick Andrew

**Comment by killdashnine420** [comment]
Just tried your trick and it worked on the Win10! Thanks Andrew!!!

**Comment by az0** [comment]
@lolinajdi 
Any chance to try the recommendation (see Feb 14 comment)? Either way, please reply here

I am closing the ticket. If the same issue happens, reopen this ticket.

**Comment by az0** [comment]
> Just tried your trick and it worked on the Win10! Thanks Andrew!!!

@killdashnine420 

Glad to hear it worked!

**Comment by az0** [comment]
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) which has the fix for the error "msvcr100.dll was not found."**  (A separate installation of the Microsoft Visual Studio runtime is no longer needed.) If you still see an issue with msvcr100.dll, reopen this issue.

While testing that, please also check that there are no issues with the digital certificate. When running the installer and running the application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.
