### ISSUE TITLE
Just an FYI -- Easy Fix

### ISSUE THREAD

**Issue by dd333** [bleachbit/bleachbit#1639]
BleachBit-4.6.0-portable gets the msvcr100.dll errors.  Has no msvcr100.dll included.  
BleachBit-4.4.2-portable does include a msvcr100.dll, and when this is copied over to BleachBit-4.6.0-portable root folder, all seems to work fine.

**Comment by az0** [comment]
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) which has the fix for the error "msvcr100.dll was not found."**  (A separate installation of the Microsoft Visual Studio runtime is no longer needed.) If you still see an issue with msvcr100.dll, reopen this issue.

While testing that, please also check that there are no issues with the digital certificate. When running the installer and running the application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.
