### ISSUE TITLE
Bleachbit 4.6.0 error on Win 10

### ISSUE THREAD

**Issue by Drdjango0104** [bleachbit/bleachbit#1665]
**Describe the bug*
After the program is installed, I attempt to run it, the attached error occurs. The code execution cannot proceed because msvcr100.dll was not found. Reinstalling the program may fix the problem.
I searched my system32 folder, and msvcr100.dll is there. Your help would be greatly appreciated. 

The error happens (every time).

**Expected behavior**

**Screenshots**

![Bleachbit error 4 6 0](https://github.com/bleachbit/bleachbit/assets/168869902/15d1283e-a6df-4bc9-8ad5-e2920d43567f)

**Desktop (please complete the following information):**
 - Windows 10
 - BleachBit version [e.g., 4.6.0]

**Additional context**

**Comment by rados** [comment]
This issue is documented in the [known issues](https://www.bleachbit.org/news/bleachbit-460) of the 4.6.0 release notes, and the fix is already coded for the next release. You can try it out now from the [CI build site](https://ci.bleachbit.org/).

**Comment by Drdjango0104** [comment]
Thanks, I will

**Comment by az0** [comment]
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) which has the fix for the error "msvcr100.dll was not found."**  (A separate installation of the Microsoft Visual Studio runtime is no longer needed.) If you still see an issue with msvcr100.dll, reopen this issue.

While testing that, please also check that there are no issues with the digital certificate. When running the installer and running the application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.
