### ISSUE TITLE
Need help.. anyone know why I can't install?  

### ISSUE THREAD

**Issue by JulieAd** [bleachbit/bleachbit#1671]
![20240516_202653](https://github.com/bleachbit/bleachbit/assets/170057933/762c0f74-0670-4f95-8ab7-99ba41e225fd)

Hi I need help with installation. does anyone know what this means?

**Comment by az0** [comment]
See known issues section here https://www.bleachbit.org/news/bleachbit-460

**Comment by az0** [comment]
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) which has the fix for the error "msvcr100.dll was not found."**  (A separate installation of the Microsoft Visual Studio runtime is no longer needed.) If you still see an issue with msvcr100.dll, reopen this issue.

While testing that, please also check that there are no issues with the digital certificate. When running the installer and running the application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.
