### ISSUE TITLE
bleach bit load/run problem

### ISSUE THREAD

**Issue by tiabohs** [bleachbit/bleachbit#1673]
on install I get: fc-cache.exe msvcr.dll error prevents install 
what is correction?
Don't tell me to reinstall or reload...done that umpteen times. You can't do the same thing over & over
an expect a diff result.
P.S. Your acct set-up & log-in procedure SUCKS!

**Comment by az0** [comment]
> on install I get: fc-cache.exe msvcr.dll error prevents install what is correction? 

Please read the[ known issues](https://www.bleachbit.org/news/bleachbit-460#known_issues) section of the release notes, which has a link to a Microsoft runtime that will help.

> Don't tell me to reinstall or reload...

Don't reinstall or reload

>  P.S. Your acct set-up & log-in procedure SUCKS!

GitHub is its own platform

**Comment by az0** [comment]
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) which has the fix for the error "msvcr100.dll was not found."**  (A separate installation of the Microsoft Visual Studio runtime is no longer needed.) If you still see an issue with msvcr100.dll, reopen this issue.

While testing that, please also check that there are no issues with the digital certificate. When running the installer and running the application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.
