### ISSUE TITLE
Bleachbit shows only boxes

### ISSUE THREAD

**Issue by endolane** [bleachbit/bleachbit#1676]
Bleachbit used to work on my system and now it just shows boxes instead of menu item.
How can i fix this?  I have uninstalled and reinstalled several times the latest version.  Even made a small donation just now and it still doesn't work correctly.
Using DELL desktop i7 core with Windows 11.

![Screenshot 2024-05-20 131951](https://github.com/bleachbit/bleachbit/assets/170360146/766c8aec-8be2-487e-8e88-8f2a6a3f455c)

**Comment by az0** [comment]
This looks like [past issues with fonts](https://www.google.com/search?q=bleach+bit+Windows+font+boxes&oq=bleach+bit+Windows+font+boxes&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIJCAEQIRgKGKABMgkIAhAhGAoYoAEyCQgDECEYChigATIJCAQQIRgKGKAB0gEIMjc5MmowajeoAhSwAgE&client=ms-android-samsung-rvo1&sourceid=chrome-mobile&ie=UTF-8).

Is Microsoft Windows set to English? 

Thank you for the donation, though it doesn't affect how the software works.

**Comment by az0** [comment]
My general advice for this issue is uninstall your version and install the latest version (currently 4.6.1 beta). During installation, watch for any errors in the installation log. There is a process that runs to build font cache, and during this you may see a black pop-up window: do not close this window. It may a few minutes for it to run.

I have not seen a response from the May 20 comment. If you are still interested in troubleshooting, please reopen this issue ticket.
