### ISSUE TITLE
MSVCR100.dll not installed

### ISSUE THREAD

**Issue by MossLaw** [bleachbit/bleachbit#1694]
I've downloaded the latest version of BleachBit 4.6.0, windows and portable and during installation, an error message pops up stating MSVCR100.dll did not install with a C: window in the background. When I attempt to run BleachBit, I get the same error. When I search for MSVCR100.dll I can find it in C:Windows\System32 and 9 other locations.

![msvcr100 dll](https://github.com/bleachbit/bleachbit/assets/174083481/d5fa137e-34c8-4f0d-a57a-b419dd6e08bc)

I reset this computer and am adding programs back. Bleachbit is one of them. My other computer I reset it loaded perfectly.

I've tried uninstalling, restarting the computer and installing it again. Same error. I tried running the portable version and same error on loading and attempting to run BleachBit

This is the error message when I attempt to start bleachbit.
![Error 1](https://github.com/bleachbit/bleachbit/assets/174083481/a9bcec96-410d-4871-84e4-15b30ec7d7b1)

This is the error message I get when trying to install any version of BleachBit

![Error 2](https://github.com/bleachbit/bleachbit/assets/174083481/1a16b739-7c4a-4cfe-98a9-9ccc3bcb784e)

Toshiba Satellite running
Edition	Windows 10 Pro
Version	22H2
Installed on	‎6/‎19/‎2024
OS build	19045.4529
Experience	Windows Feature Experience Pack 1000.19058.1000.0

Device name	DESKTOP-AGDQ2HG
Processor	Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz   2.20 GHz
Installed RAM	8.00 GB
Device ID	30B5138C-4E87-4F3C-AFD2-606F4FFF69DE
Product ID	00330-80205-46461-AA050
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

BleachBit 4.6.0

Any ideas? Thanks

Jim

**Comment by SuperCuek** [comment]
https://www.bleachbit.org/news/bleachbit-460#known_issues

**Comment by az0** [comment]
@MossLaw 
Did the link that SuperCuek posted to the known issues helps? Basically, you install that file yourself via the Microsoft Runtime.

**Comment by az0** [comment]
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) which has the fix for the error "msvcr100.dll was not found."**  (A separate installation of the Microsoft Visual Studio runtime is no longer needed.) If you still see an issue with msvcr100.dll, reopen this issue.

While testing that, please also check that there are no issues with the digital certificate. When running the installer and running the application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.
