### ISSUE TITLE
Lost whole disk after wiping free space.

### ISSUE THREAD

**Issue by Kali273** [bleachbit/bleachbit#1697]
When i used wiping free space so temp file filled my disk and before the end of process popped up some error. So i closed BleachBit and deleted the temp file. But i had no access to files on that disk and after i restarted pc windows did not load that disk at all..
So now i lost all files on disk or what i can do?
win11, BleachBit 460

**Comment by az0** [comment]
> When i used wiping free space so temp file filled my disk and before the end of process popped up some error.

Do you have a record of the error message? If so, please paste it here verbatim.

> So i closed BleachBit and deleted the temp file. But i had no access to files on that disk and after i restarted pc windows did not load that disk at all..

Your Windows is on C: and the drive you wiped was another drive like D: , is that right? 

The disk with the problem is an internal HDD, internal SSD, or removable drive?

Could you tell me more about the "did not load that disk at all": what happens when you try to load it? Do you have a record of the error message? If so, please paste it here verbatim.

**Comment by Kali273** [comment]
I dont have a record. But looked the same as here... `https://github.com/bleachbit/bleachbit/issues/978`
It was internal ssd, not system disk. After error when i clicked on any folder in that drive, so win popup Location doesnt exist. After windows restart that drive disappeared from This PC Devices and Drives..
In Disk management it says device doesnt exist. But when i clicked Rescan Disks that missing disk again started working. I again deleted that big temp file and finally all on the disk working good..
So somehow that wipe process disconnected the disk or something like that,,

**Comment by az0** [comment]
BleachBit's wipe process uses basic functionality to create files, write data to them, and delete them. It does _not_ do anything special or dangerous, like using special Windows APIs, bypassing normal Windows APIs, disconnecting devices, or formatting the partition. The most special thing about the wiping process is that it causes heavy I/O, so perhaps the SSD device became overheated or something like that.

You may wish to not often wipe the free space. If you want to do it more often, a trick you can consider is leaving a large empty file, so the frequent wiping operates on a smaller space. Say you have a 1 TB SSD and you normally using 200GB: then you could create a 700GB empty file, so BleachBit has to wipe only 100GB instead of wiping 800GB. This will be much faster and less stressful for the SSD.

In this example, you could create 7 x 100 GB files, so if you need the extra space, you can just delete some of the 100GB files. If you need less space, just copy the 100GB files to reserve more space.

**Comment by az0** [comment]
Sorry, this looks like a hardware failure, not a software bug
