### ISSUE TITLE
Please upload the new version of Bleachbit with the fix

### ISSUE THREAD

**Issue by Xelbayria** [bleachbit/bleachbit#1708]
### DETAILS: 

I don't need to report the bug because i see it's already fixed. but it's been 8 months since `Fix missing DLL` was included in the source code. The date for 4.6.0 was `Nov 6, 2023` and the fix was applied on `Nov 17, 2023`. I am using Portable version. 

The version 4.6.0 need to be updated with the fix. I can't use bleachbit without the missing DLL.

**Comment by az0** [comment]
Did you see the [known issues](https://www.bleachbit.org/news/bleachbit-460#known_issues)? You can get the build from the [BleachBit CI site](https://ci.bleachbit.org/), add the DLL to the 4.6.0 you already have, or downgrade to 4.4.2. However, I cannot sign the new build and release it because my digital certificate expired, and there is an issue with the replacement.

**Comment by Xelbayria** [comment]
oh ok. I can downgrade to 4.4.2. 

> I cannot sign the new build and release it because my digital certificate expired, and there is an issue with the replacement.

gotcha

**Comment by az0** [comment]
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) which has the fix for the error "msvcr100.dll was not found."**  (A separate installation of the Microsoft Visual Studio runtime is no longer needed.) If you still see an issue with msvcr100.dll, reopen this issue.

While testing that, please also check that there are no issues with the digital certificate. When running the installer and running the application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.

**Comment by Xelbayria** [comment]
Forgot to tell you, it's working properly. Have a good day!
