### ISSUE TITLE
quali file pulire con bleachbit

### ISSUE THREAD

**Issue by eburum545** [bleachbit/bleachbit#1746]

**Comment by az0** [comment]
Which files you would like to clean the depens on your goals. Are you concerned about recovering disk space? Are you worried about protecting your privacy by removing private information? Is there information that you might regret deleting? 

For example, deleting cookies doesn't delete much disk space. It can help some with privacy, but it creates an inconvenience because you have to log into websites again.

**Comment by az0** [comment]
There was no reply, so I am closing this. If you have a follow-up question, add a comment to this issue ticket and reopen the issue ticket.

A quick answer is that these options are generally safe  and will save the most space: cache, backup files, logs, vacuum. For privacy, you may wish to delete history and cookies, but this can also be inconvenient for some people.

Some more info is in the [FAQ](https://docs.bleachbit.org/doc/frequently-asked-questions.html) under "should I delete cache" and "should I delete cookies."
