### ISSUE TITLE
Easytag cleaner

### ISSUE THREAD

**Issue by ROCKNROLLKID** [bleachbit/bleachbit#176]
https://github.com/bleachbit/bleachbit/blob/master/cleaners/easytag.xml

Easytag has a Windows version, but I do not know if the cleaning rules apply the same for Windows.

**Comment by az0** [comment]
Yes, it is inconsistent that the Linux version is supported by not Windows. If this issue is to add support for Windows, please feel free to do so. In that case, please reopen this issue or open a pull request. Here is the installer
https://download.gnome.org/binaries/win32/easytag/2.4/easytag-2.4.3-setup.exe

Thanks!
