### ISSUE TITLE
Move the english only BleachBit for Windows to a zip file

### ISSUE THREAD

**Issue by ROCKNROLLKID** [bleachbit/bleachbit#207]
Since it was mainly designed to be a smaller, more lightweight version of BleachBit and also more for limited bandwidth users, let's move it to a zip archive. Maybe to a 7z archive format, since it is the smallest kind of archive for Windows.

**Comment by az0** [comment]
You mean it would be portable (i.e., it cannot be installed)?

**Comment by ROCKNROLLKID** [comment]
You could make it portable, but this idea was to just move the installer into a archive file to help shrink it down now. After much time thinking, it is probably not necessary, but I will leave it up for you to decide.

**Comment by az0** [comment]
I tested archiving the latest Windows English binary

_Command_

````
7z a -t7z BleachBit-1.17-setup-English.7z -m0=lzma2 -mx=9  BleachBit-1.17-setup-English.exe
````

_Results_

BleachBit-1.17-setup-English.exe: 7,957,272 bytes
BleachBit-1.17-setup-English.7z: 7,928,479 bytes

The size improvement is very small because the NSIS installer is optimized for size.  BleachBit is configured to use NSIS with solid LZMA compression, which is used also in 7-zip.
