### ISSUE TITLE
Move all cleaners to CleanerML

### ISSUE THREAD

**Issue by nodiscc** [bleachbit/bleachbit#212]
https://github.com/bleachbit/bleachbit/pull/86#issuecomment-127828627:

> move more of the cleaning options out of Python and into CleanerML.

@az0 is your long term goal having all cleaners in https://github.com/az0/cleanerml? If so I can start porting cleaners in https://github.com/bleachbit/bleachbit/tree/master/cleaners there.

Just getting updated cleaners as part of normal bleachbit updates would satisfy me (a git-based update mechanism can come later). Eg. adapt the makefile:

```
dependencies:
    rm cleaners
    git clone https://github.com/az0/cleanerml
    mv cleanerml/release cleaners
    rm cleanerml
```

Cleaners in `release/` are currently in a good state.

**Comment by ROCKNROLLKID** [comment]
Sounds good to me.

I think we should also move the CleanerML respo to BleachBit respo (instead of az0) because I don't many people really know it even exists and also it will all be in 1 respo, too, so it is more organized and easier to access.

**Comment by nodiscc** [comment]
Or @az0 could move the  `release` cleaners to the main bleachbit repo for tighter control, and rename the cleanerml repo to `cleanerml-testing`. It would become a repo for reviewing/testing proposed/unsafe cleaners only.

**Comment by az0** [comment]
@nodiscc 
Instead of moving all the cleaners from CleanerML into BleachBit, I was planning to set up an optional subscription with over-the-air updates, sort of how Winapp2.ini works now in BleachBit. This allows for faster updates and avoids change conflicts when an old version is in the BleachBit application, though lately there have not been many updates.

That has taken a while to get started, so the Makefile adjustment sounds good for the release after BleachBit 2.0. I am trying to get the final version out the door soon.

@ROCKNROLLKID 
To help people find the CleanerML repository I have set up many links to it, and I plan to move it from the az0 namespace to the BleachBit organization. Still, I agree that it is relatively hard to find for regular users.
