### ISSUE TITLE
Bleachbit Preferences menu doesn't open after Memory cleaning (GNU+Linux)

### ISSUE THREAD

**Issue by theatre-x** [bleachbit/bleachbit#228]
Andrew,

I brought this up a year or two back. I forgot all about this problem until I just ran into it again and, thanks to the scientific method, was able to come up with a more promising lead.

If you open BB as root and select the "Memory" option under System, run the cleaning, then go to Edit > Preferences, the preferences menu doesn't open. I haven't experienced this on Windows due to not even attempting it in the first place, only on GNU+Linux.

Can you recreate this bug I am experiencing as well? I'm using BB 1.12 and have seen this occur on Lubuntu and Mint so far.

**Comment by theatre-x** [comment]
It seems that when you execute BB from a shell, this does not occur. It only occurs from Lubuntu apps menu when you select "Bleachbit (as root)".

**Comment by theatre-x** [comment]
In case someone reading this has no idea what I am referring to with the whole "menu" part mentioned in my previous comment, here's the actual shell command: `su-to-root -X -c bleachbit`

Run that, and then perform my steps above to test.

**Comment by az0** [comment]
I tried BleachBit 1.17 (git 71f418cba29ebc7b9d84ef9ecfc6c4521abac4e8) on Ubuntu 16.04 (GNOME), and I ran the su-to-root from the console (rather than using the launcher). The preferences dialog launched OK, and also I could open the help-about dialog.

Later when I closed BleachBit, I saw this error on the console:

````
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
````

@theatre-x : Did you see an error like this? What if you run su-to-root from a console?

**Comment by theatre-x** [comment]
Let me try it and get back to you.

**Comment by theatre-x** [comment]
I forgot to test for the su-to-root bit mentioned above but I will get to it later. However, I wonder if this is related to the original issue?

> Traceback (most recent call last):
  File "/usr/share/bleachbit/GUI.py", line 493, in cb_preferences_dialog
    pref = PreferencesDialog(self.window, self.cb_refresh_operations)
  File "/usr/share/bleachbit/GuiPreferences.py", line 64, in __init__
    notebook.append_page(self.__general_page(), gtk.Label(_("General")))
  File "/usr/share/bleachbit/GuiPreferences.py", line 111, in __general_page
    options.set('auto_start', swcc())
  File "/usr/share/bleachbit/Options.py", line 246, in set
    self.__flush()
  File "/usr/share/bleachbit/Options.py", line 76, in __flush
    General.makedirs(bleachbit.options_dir)
  File "/usr/share/bleachbit/General.py", line 118, in makedirs
    makedirs(parentdir)
  File "/usr/share/bleachbit/General.py", line 119, in makedirs
    os.mkdir(path, 0o700)

**Comment by az0** [comment]
It looks related because it is calling GuiPreferences.

That looks like only a partial traceback. The last line should have some kind of error: RuntimeError, IOError, OSError, etc.

Either way, code committed October 2016 (which is newer than BleachBit 1.12) removes su-to-root in favor of pkexec, and this may avoid the traceback (crash) you saw. In other words, the newer versions maybe fixed the traceback.

**Comment by theatre-x** [comment]
I got this after running it again: OSError: [Errno 13] Permission denied: '/root/.config'

**Comment by az0** [comment]
@theatre-x 

Are you able to reprodue this with BleachBit version 2.2 or later? Testing version 2.3 would be even better because of major GUI changes after version 2.2

**Comment by az0** [comment]
If the menu continues not to open, please reopen this issue ticket
