### ISSUE TITLE
Firefox/Error in execution of <bleachbit.Command.Function instance at 0x01B1AC88>

### ISSUE THREAD

**Issue by nico92GitHub** [bleachbit/bleachbit#238]
Hello!
I used Beachbit regularly under Seven (Intel Pentium E5700) and I did not encounter any error.
Since I have my new machine (Intel Celeron J1900), always under Seven, I always encounter the error indicated in the subject at the end of a cleaning.
After these errors, I did not notice any malfunction.
I hope you will have a moment to give me your opinion on this error "bleachbit.Command.Function".
Best regards,
Nicolas
![tilt_bleachbit](https://user-images.githubusercontent.com/22394276/31048383-42d469d8-a61c-11e7-9a7d-d149887ce2f3.jpg)

**Comment by ROCKNROLLKID** [comment]
What BleachBit version?

What operating system (looks like Windows).

Can you try BleachBit 1.17 beta and see if this still happens: https://www.bleachbit.org/news/bleachbit-117-beta

**Comment by nico92GitHub** [comment]
The error occurs with the stable version 1.12, but also with the 1.17.
I'm admin of my machine witch is a Windows under Seven Ultimate.
Motherboard: Biostar Group J1900NH3. Memory: 8 Gb.
Hard disk: Samsung SSD 850 EVO 500 Gb.
My protection AV: Eset NOD32, firewall: Spyshelter.
Attachments: Screen view and ini file in text format.

I remain at your disposal...
Nico

[BleachBit-ini.txt](https://github.com/bleachbit/bleachbit/files/1347015/BleachBit-ini.txt)

![tilt_bleachbit_1-17](https://user-images.githubusercontent.com/22394276/31052927-781f57fe-a691-11e7-9ba7-8dd781a5540f.jpg)

**Comment by kevowe** [comment]
Hi, I believe this issue is related to what I'm also experiencing.

I've narrowed it down to happening when cleaning the URL history on Firefox.  The URL history is not cleared on Firefox when this error occurs.  I've tested this with both Firefox 55 and Firefox 56.  

I was able to reproduce this issue on three different computers all running Windows 10 Pro x64.  The issue occurred in both BleachBit 1.12 and 1.17 beta.

Below are some screenshots of both the preview and clean operation in which only Firefox URL History is selected.

Preview Operation
![bleachbit_preview_firefox_url_history](https://user-images.githubusercontent.com/15938560/31054456-91687dc6-a678-11e7-93f9-0ef71b8be3d3.PNG)

Clean Operation
![bleachbit_clean_firefox_url_history](https://user-images.githubusercontent.com/15938560/31054458-971a06e0-a678-11e7-98a6-61decea4d3ac.PNG)

**Comment by nico92GitHub** [comment]
Hello!
I tested like you by checking only URL history Firefox. Yes, the error comes from there, without removing anything.
Just one precision, my browser is Pale Moon, which uses the same locations as Firefox.
The most important thing is to have identified this error. So at my user level, this issue can be closed.
One last question, do you advise me to use version 1.17 or stay on the 1.12? As a matter of principle, I leave aside the BETA versions ...
In any case, thank you for your support :)
Cordialement,
Nico

**Comment by ROCKNROLLKID** [comment]
Thank you guys for your detailed report. We will look into this issue and see what the cause is, but please be patient. We are unsure what exactly is causing this. For now, I would suggest either manually deleting the files or just unchecking the entry until this is resolved.

**Comment by az0** [comment]
A week ago I added a fix for the error `Fix DatabaseError: no such table: moz_favicons` that can cause errors when cleaning Firefox URL history. The symptim is the `Error in execution of ...` message. You can test an early release from http://ci.bleachbit.org/ by choosing version 1.17.573 or later, or soon I hope to publish the same code it as a beta version.

**Comment by az0** [comment]
Please test [BleachBit version 1.19 beta](https://www.bleachbit.org/news/bleachbit-119-beta) and reply in this bug ticket with how it goes. Also, please reopen this ticket if the error messages continues.
