### ISSUE TITLE
Drop support for the old opera 12.x version

### ISSUE THREAD

**Issue by pitsi** [bleachbit/bleachbit#243]
Opera 12.x is obsolete now. How about removing its cleaner file (cleaners/opera.xml) completely and/or replacing it with opera 15+ (opera_cef) as mentioned on #127 ?

**Comment by az0** [comment]
I propose to leave #127 open to support the newer Opera and to leave support for the old Opera. 

It's generally good to not remove support for obsolete applications/browsers because a user may still have old junk files from a long time ago. In this case, maybe the user used Opera long ago but never upgraded.

As time goes on, the probability of this shrinks. Opera 15 was released July2013, so there may still be some users with the older junk files.

**Comment by pitsi** [comment]
I agree with what you say about that... forgotten user, but please add support for the new opera in bleachbit then. Rename the old cleaner to opera-legacy for instace and add the new one as opera.
Having a cleaner which no longer works out of the box for the new versions of opera is really annoying, because the user has to search and install the opera-cef cleaner. 
And even that cleaner (opera-cef) needs some refreshing too, because it has to support opera-beta and opera-developer as well.

**Comment by pitsi** [comment]
Sadly, bleachbit 2.0 was released a few hours ago and the cleaner for opera still points at old opera 12.x files. And no sign of opera-cef cleaner in the new cleaners list.
Why do you really keep supporting obsolete stuff?

**Comment by az0** [comment]
FYI, there recently have been commits that give good support for Opera

**Comment by az0** [comment]
Yes, the new `opera.xml` is not backwards compatible to BleachBit version 2.0 (final release). The new CleanerML requires the new Python code. 

You can preview the new code now like this

See https://docs.bleachbit.org/dev/running-from-source-code.html

````
git clone https://github.com/bleachbit/bleachbit.git
cd bleachbit
python bleachbit.py
````

**Comment by pitsi** [comment]
Oh well... I will wait for the new version then.
