### ISSUE TITLE
Bleachbit 2.0 won't install on *buntu 17.10 through the .deb installer

### ISSUE THREAD

**Issue by WPFilmmaker** [bleachbit/bleachbit#304]
Gdebi  throws a "an older version is available in an older channel" and then it closes itself. Any way to push the 2.0 into 17.10 or at the least is there a way to force gdebi to install it?

**Comment by az0** [comment]
Ubuntu does not update BleachBit except with updates to Ubuntu. In other words, the version that came with Ubuntu 17.10 will always be the same. Ubuntu 18.04 is the next change for a newer version.

I'll look into that message. For now, a few things you could try

1. Use a different package manager GUI: Software Center, Synaptic, and Apper

2. Use the apt or dpkg command line interface

3. Clear the package cache with `sudo apt-get clean` so that maybe gdebi won't notice the other version

**Comment by WPFilmmaker** [comment]
@az0 Thanks a lot about the tips!

**Comment by abitrolly** [comment]
@WPFilmmaker looks like the issue can be closed then.

**Comment by WPFilmmaker** [comment]
yes

**Comment by abitrolly** [comment]
@WPFilmmaker thanks!
