### ISSUE TITLE
Bleachbit 2.0 in Ubuntu 18.04 (aka the next LTS release supported for 5 years)

### ISSUE THREAD

**Issue by WPFilmmaker** [bleachbit/bleachbit#305]
According to https://launchpad.net/ubuntu/bionic/+source/bleachbit the version of BleachBit shipped in the next LTS release of Ubuntu (supported for 5 years) is bleachbit_1.15-2. Do devs have a way to push BB 2.0 into Bionic Beaver?

Here is the release schedule for Ubuntu 18.04: https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule

**Comment by AsciiWolf** [comment]
There is also [this ugly bug](https://bugs.launchpad.net/ubuntu/+source/bleachbit/+bug/1752875) in the current Ubuntu version. You can do [freeze exception](https://wiki.ubuntu.com/FreezeExceptionProcess) after the new version will be available in Debian or at least make patches for the old version to fix important bugs. I personally really hope that the bug #1752875 will be fixed in 18.04 as GNOME Software does not uninstall dependencies in Ubuntu so the autoremove feature is important for users.

**Comment by az0** [comment]
Yes, it would be great to get the update into the Ubuntu repositories. Debian and Ubuntu have package maintainers that do this. In other words, they "pull" it rather than me "pushing" it. 

Today I marked the release on Launchpad
https://launchpad.net/bleachbit/+milestone/2.0

This flags it on their page here
https://launchpad.net/ubuntu/bionic/+source/bleachbit

If this does not work, you can try contacting the maintainers. Maybe it is through a bug ticket on Launchpad or email to the maintainers. I am not sure the official way to contact them.
