### ISSUE TITLE
Slow start in v2

### ISSUE THREAD

**Issue by nico92GitHub** [bleachbit/bleachbit#309]
Hello!
I notice a slowness at startup of tens of seconds since version 2.
Before in version 1, it happened rarely and randomly.
I left the setting as original.
My machine is under seven 32 bit on an SSD drive.
Do you have any idea where this may come from ???
In the waiting for your answer,
best regards,
Nicolas

**Comment by az0** [comment]
You are using Windows 7 32 bit?

Do you have winapp2.ini enabled?


Andrew


On Mar 9, 2018 04:16, "nico92GitHub" <notifications@github.com> wrote:

Hello!
I notice a slowness at startup of tens of seconds since version 2.
Before in version 1, it happened rarely and randomly.
I left the setting as original.
My machine is under seven 32 bit on an SSD drive.
Do you have any idea where this may come from ???
In the waiting for your answer,
best regards,
Nicolas

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bleachbit/bleachbit/issues/309>, or mute the thread

**Comment by nico92GitHub** [comment]
Re: [bleachbit/bleachbit] Slow start in v2 (#309)



Yes, I have Windows 7 32 bit, but I do not have the winapp2.ini file.
Where can I find this file? And where should this file be copied?

Nico


You are using Windows 7 32 bit?

Do you have winapp2.ini enabled?


Andrew


On Mar 9, 2018 04:16, "nico92GitHub" <notifications@github.com> wrote:

Hello!
I notice a slowness at startup of tens of seconds since version 2.
Before in version 1, it happened rarely and randomly.
I left the setting as original.
My machine is under seven 32 bit on an SSD drive.
Do you have any idea where this may come from ???
In the waiting for your answer,
best regards,
Nicolas

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bleachbit/bleachbit/issues/309>, or mute the thread

**Comment by az0** [comment]
Winapp2.ini will be automatically downloaded if selected in the bleachbit
options. I asked because this may slow down the startup, but you say you do
not have it

Which antivirus software do you use?

**Comment by nico92GitHub** [comment]
Re: [bleachbit/bleachbit] Slow start in v2 (#309)



I also thought that my antivirus could play tricks for a while and not after a period ... I have ESET NOD32.

Nico




Winapp2.ini will be automatically downloaded if selected in the bleachbit
options. I asked because this may slow down the startup, but you say you do
not have it

Which antivirus software do you use?

**Comment by az0** [comment]
I am not sure why re-downloading would help. It should be the same.

If you have this trouble again, try using [ESET's instructions to temporary disable the antivirus](https://support.eset.com/kb548/) only for troubleshooting purposes. If startup is often slower with the antivirus enabled, then it is the fault of the antivirus. Remember to turn the antivirus back on after troubleshooting. 

You wrote "the incident is over," so I will close this issue now.
