### ISSUE TITLE
Access denied when cleaning some system files

### ISSUE THREAD

**Issue by WilliamBeltranC** [bleachbit/bleachbit#337]
The description of this issue is detailed in the following thread:
https://www.bleachbit.org/forum/errors-when-cleaning-bleachbit-20

**Comment by az0** [comment]
I do not get access denied deleting the CBS log (as reported on the forum), but with the latest BleachBit I do get access denied when deleting this log (option: Winapp2 - Microsoft Windows - Windows Update).

[Error 5] Acceso denegado.: Command to delete C:\Windows\Logs\waasmedic\waasmedic.20190724_040722_109.etl

**Comment by az0** [comment]
@WilliamBeltranC 
Thank you for your patience. Does BleachBIt 3.0 have this problem?

**Comment by WilliamBeltranC** [comment]
Hi, Andrew,
I've recently got this errors

Error: windows_defender.backup: Command to delete C:\ProgramData\Microsoft\Windows Defender\Definition Updates\Backup\mpavdlta.vdm
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 88, in execute
  File "bleachbit\Command.pyo", line 84, in execute
  File "bleachbit\FileUtilities.pyo", line 340, in delete
  File "bleachbit\FileUtilities.pyo", line 725, in wipe_contents
  File "bleachbit\WindowsWipe.pyo", line 923, in file_wipe
  File "bleachbit\WindowsWipe.pyo", line 434, in open_file
error: (5, 'CreateFileW', 'Acceso denegado.')
Error: windows_defender.backup: Command to delete C:\ProgramData\Microsoft\Windows Defender\Definition Updates\Backup\mpasdlta.vdm
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 88, in execute
  File "bleachbit\Command.pyo", line 84, in execute
  File "bleachbit\FileUtilities.pyo", line 340, in delete
  File "bleachbit\FileUtilities.pyo", line 725, in wipe_contents
  File "bleachbit\WindowsWipe.pyo", line 923, in file_wipe
  File "bleachbit\WindowsWipe.pyo", line 434, in open_file
error: (5, 'CreateFileW', 'Acceso denegado.')
Error: system.tmp: Command to delete C:\Windows\temp\L\nisfull.vdm
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 88, in execute
  File "bleachbit\Command.pyo", line 84, in execute
  File "bleachbit\FileUtilities.pyo", line 340, in delete
  File "bleachbit\FileUtilities.pyo", line 725, in wipe_contents
  File "bleachbit\WindowsWipe.pyo", line 923, in file_wipe
  File "bleachbit\WindowsWipe.pyo", line 434, in open_file
error: (5, 'CreateFileW', 'Acceso denegado.')

I guess the Windows Defender ones are new. I tried updating WD but error is still there.

**Comment by az0** [comment]
Thanks for the update.

What this looks like is that the files are locked because they are in use by the system, so they can't be wiped. It's not a big problem because generally we don't want to wipe files that are in use, but BleachBit could still handle the situation better. Potential solutions are: queue for deletion on reboot, whitelist them, or quiet the error message.

**Comment by Tobias-B-Besemer** [comment]
If you will whitelist all files that can be looked, I guess you will have a lot to do and then you should maybe often make new BB updates, that the whitelist gets always updated.

I see also by this solution and the last solution (just ignore, as I understand it) then problem, that a user maybe expect that all files get wiped, but BB will not do it because the file is whitelusted ir just get ignored because of it's state.

But I see a other pissible solution, too:
Force unlook the files!
I guess this should normally not be done, because uf done e.g. with a file that is needed and looked by the OS, the system can get unstable/hang/crash/etc. ...
Pissible solution for this could IMHO be, that BB does it only if it gets tell to do so in any way. (Yes, something like a whitelusting, again, but at least not in the Python code of BB.)
To tell BB where it is save to force unlook files, one solution could be UMHO be, that we do it in the cleaner files.
Cleaner files can also be easier and mire often be released then BB itself.
So maybe add a "you can force unlook this files' switch/parameter to those cleaner files that get recognized that zhey should have it and where it should be save to do it.
So I think Windows Defender or Windows Lig file cleaner should be possible candidates to use the switch.

https://stackoverflow.com/questions/1320812/detect-and-delete-locked-file-in-python
https://stackoverflow.com/questions/48675286/how-do-i-unlock-locked-files-and-folders-mac-with-python
https://stackoverflow.com/questions/25297601/python-delete-locked-file

**Comment by Tobias-B-Besemer** [comment]
@az0, in this issue https://github.com/bleachbit/bleachbit/issues/536 it seems that files are looked, too! Maybe the same issue/solution...

**Comment by Tobias-B-Besemer** [comment]
OK Andrew, here is a more detailed explanation of how I would solve the issue... Maybe its helps you...

I would extend the definition of command="delete" in CleanerML in so far, that when a line in a cleaner file with command="delete" completely at the end e.g. a switch="force" have, each file that should gets deleted gets force unlocked.
I would define the switch="force" rule completely at the end of the line, because this makes implementation maybe easierer, but surely the change of the cleaner line, the readiness of the cleaner code & the check of the rule if "force" is directed or not!
So it seems the code of BB should then get in this case improved in this way, that when BB find a comnand="delete" line in a cleaner file, it first must check the last letters of the line for the string switch="force" + end of XML line code, and then runs the bew additional code to force unlock on each file it finds where the line code fits.
I would use "switch" in the code because we/you will maybe in the next years will find more cases where a cleaner command should get improved (maybe already in the "globe" after "walk.all" case?) and then you have the chance to extended those commands always with the same clear defind code/word "switch" with the each keyword for the special case after it.

But as always: This are just some creative ideas/suggestions that should inspire you, and nothing else!

**Comment by mkhon** [comment]
I see "Access Denied" for files like "C:\Windows\Logs\waasmedic\waasmedic.20200419_171709_135.etl"
Such files just don't have write permission ACL

**Comment by az0** [comment]
Max made a change to allow BleachBit to delete more files. Please try build 4.0.1.1642 (or later) from the [CI site](https://ci.bleachbit.org/). It should be there in ~10 minutes. Please let me know how it goes by adding a comment here.

**Comment by az0** [comment]
FYI, there is a digitally-signed Windows installer with this fix available via the [BleachBit 4.1.0 beta](https://www.bleachbit.org/news/bleachbit-410-beta) page
