### ISSUE TITLE
Windows shellbags

### ISSUE THREAD

**Issue by ofereitan** [bleachbit/bleachbit#353]
Does bleachbit delete shellbags?

Thx,
Ofer

**Comment by az0** [comment]
Do you mean like explained in the article [Windows Shellbag Forensics](http://www.williballenthin.com/forensics/shellbags/)?

**Comment by ofereitan** [comment]
yes

**Comment by ROCKNROLLKID** [comment]
Winapp2 has a entry for Shell bags. You can use Winapp2 by enabling it in preferences in BleachBit, then check "Use community cleaning rules (Winapp2)."

**Comment by ofereitan** [comment]
The shellbags cleaner is missing in the bleachbit version of winnap2 (https://github.com/bleachbit/winapp2.ini/blob/master/Winapp2-BleachBit.ini)

**Comment by Tobias-B-Besemer** [comment]
> Winapp2 has a entry for Shell bags. You can use Winapp2...

E.g. "Shellbag Analyzer & Cleaner" from PrivaZer (https://privazer.com/de/download-shellbag-analyzer-shellbag-cleaner.php) finds much more shellbags then CCleaner + WinApp2.ini.

**Comment by Tobias-B-Besemer** [comment]
> Winapp2 has a entry for Shell bags.
Where is it ??? I can't find it in CCleaner/WinApp2.ini...

I wrote now a CleanerML file for Shell Bags:
https://github.com/az0/cleanerml/pull/165

**Comment by Jon-guy30** [comment]
> 
> 
> > Winapp2 has a entry for Shell bags.
> 
> Where is it ??? I can't find it in CCleaner/WinApp2.ini...
> 
> I wrote now a CleanerML file for Shell Bags:
> [az0/cleanerml#165](https://github.com/az0/cleanerml/pull/165)

Hi. 
I managed to get your cleaner onto my bleachbit portable. I only see one entry in the code for the shellbags, does it remove and disable all of them? There are multiple registry keys that need to be removed and recreated. I'm not sure what your cleaner does since there's no description, and it doesn't calculate what it deletes before you run it.

Here's another good article on shellbags for anyone interested https://www.ghacks.net/2014/06/09/remove-old-shellbag-entries-windows-privacy/

The article features the shellbag analyzer program as mentioned above, but I'm not willing to use it. Bleachbit really needs a good shellbag remover and disabler since there's no free software solution for this task. 

Just thought I'd share my feedback on this topic. And you're right winapp2.ini does not have shellbag analyzing functionality. I really hope it gets added to it.

**Comment by Tobias-B-Besemer** [comment]
> I only see one entry in the code for the shellbags, ...

It were two lines...

> ... does it remove and disable all of them? ...
> Here's another good article on shellbags for anyone interested https://www.ghacks.net/2014/06/09/remove-old-shellbag-entries-windows-privacy/

No, it didn't! Thx for the article! I updated my cleaner, now. ...

> There are multiple registry keys that need to be removed and recreated. I'm not sure what your cleaner does since there's no description, and it doesn't calculate what it deletes before you run it.

There is no calculation necessary! I/We delete directly the registry keys...
And we don't need to re-create any - BleachBit deletes only the folders/tree, that don't need to be re-created!

> The article features the shellbag analyzer program as mentioned above, but I'm not willing to use it. Bleachbit really needs a good shellbag remover and disabler since there's no free software solution for this task.

The shellbag analyzer program mentioned above is also "free software", because you don't need to pay for it, but it isn't "Open Source".
As already written: I updated (and uploaded) my cleaner - maybe you wanna give it a new try... ;-)

> Just thought I'd share my feedback on this topic. And you're right winapp2.ini does not have shellbag analyzing functionality. I really hope it gets added to it.

I did it now with CleanerML, not WinApp2.ini...

Btw., @az0, can you have a look at this: https://github.com/williballenthin/shellbags
It's also in Python written... Maybe you can (re-) use some code of it ???

**Comment by az0** [comment]
I marked this issue for 2.4 stable (2.3 beta)

**Comment by Tobias-B-Besemer** [comment]
OK.

**Comment by Jon-guy30** [comment]
@Tobias-B-Besemer 

Thanks for the clarification and for your effort!

Unfortunately I don't program, but I'm going to check it out again.

@az0 Thanks for taking up this issue, very cool! I'd donate but I'm not in a position to do so, all I can do is comment and share ideas,

**Comment by Tobias-B-Besemer** [comment]
No prob! You're welcome!

**Comment by LoveLace55** [comment]
I have tried this, and my shellbags are still showing. I use shellbagsview here :
http://www.portablefreeware.com/index.php?id=1638

**Comment by az0** [comment]
I moved Tobias's cleaner into the mainline Windows Explorer cleaner

**Comment by az0** [comment]
You could test this fix in the newly-released [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta)
