### ISSUE TITLE
Folder Access Denied

### ISSUE THREAD

**Issue by RodHorning** [bleachbit/bleachbit#375]
Windows 10 build 17134.165
Bleachbit 2.0

Logged in on a non-administrator account
I used BleachBit to shred a file in the User folder (found the file via Windows Explorer and right clicked). 
It seemed to work as the file name disappeared
BUT
Another file of similar size now showed. File had a name of p
Access denied trying to delete this file 
Access denied trying to delete the folder
Switched to an administrator account
Checked permissions - had full control
Access denied trying to delete the file
Access denied trying to delete the folder
Took Ownership
Access denied trying to delete the folder
Access denied trying to delete the folder

Also tried to delete the file from a command window

Started Bleachbit 
Selected Custom 
Entered the folder name
Bleachbit indicated the folder and a desktop.ini
Bleachbit indicated success
folder and file still show in explorer

**Comment by RodHorning** [comment]
Update
After a Windows reboot the Folder was gone

**Comment by az0** [comment]
This is what seems happened. The short filename was probably the original file after it was wiped, and its name was shortened to hide the original filename. The access denied happened because another process, probably a security software such as antivirus, locked the file and prevented other applications from modifying the file or its folder. After the reboot, the security software released the lock. Also, BleachBit has the ability to queue a file to be deleted on reboot.

This locking probably explains why the file with the short name remained: because the operating system would not let BleachBit finish what it was doing.

If you continue to see this, try temporarily disabling the security software for troubleshooting purposes. Some software has a "game mode" for this. If it still happens with the security software disabled, please reopen the ticket.

**Comment by RodHorning** [comment]
Thank you for your promp reply.  I understand and will give that a try.  

As an FYI The only security software I have is Windows Defender.

**Comment by az0** [comment]
OK, I will keep that in mind in case I see a pattern with other users. So far I do not recall other users having these symptoms, though I saw a similar problem with McAfee antivirus and another application (not BleachBit).
