### ISSUE TITLE
Bleachbit accessibility with screen reader on Windows

### ISSUE THREAD

**Issue by pzajda** [bleachbit/bleachbit#379]
Tested on Windows 7 64-bits, Bleachbit 2.0.
When running Bleachbit, only the windows title can be read with screen reader.
 Using Tab/Maj+Tab doesn't work at all.
I tried with NVDA, which is free and opensource software.

Do not esitate if you need more information.

**Comment by az0** [comment]
BleachBit 2.0 is built on top of the GTK+ version 2 GUI framework. I believe GTK+ 2 is designed to support accessibility, but I do not know much about it. 

Do you know whether you have tested any other GTK2+ applications on Windows with NVDA? If not, would you mind testing a few? This troubleshooting could help determine whether the issue is specific to GTK+2 or to BleachBit.

**Comment by pzajda** [comment]
I cannot ensure you I already have tested GTK+ 2 application on Windows.
Yes, I can test some GTK+ 2 applications if it can help, no problem for
that.

**Comment by pzajda** [comment]
Hello,

I've tested Pidgin which is also not accessible at all.
While looking for more information, it looks like an issue with GTK: http://nabble.nvda-project.org/GTK-with-NVDA-td39492.html
It seems accessibility has not been implemented on GTK Windows port.
I have not found any more recent information.

**Comment by az0** [comment]
@pzajda  thank you for testing. I am disappointed about the situation, but could you please consider this issue closed for now because it is up to GTK+ to provide the accessibility functionality?

There is much progress on a major upgrade for BleachBit to switch from GTK+ version 2 to version 3. I am not sure that this would solve the problem, but eventually it would help. GTK+ version 2 is no longer gets any updated, so staying on version 2 would not help.
