### ISSUE TITLE
downloaded winapp2.ini is very old

### ISSUE THREAD

**Issue by ben-page** [bleachbit/bleachbit#388]
Bleachbit downloads a version old version of winapp2.ini (180615). The update URL (https://update.bleachbit.org/update/2.0) is (apparently) hard coded to the version of winapp2 at the time of the BleachBit release. So the winapp2.ini wont be updated until a new version of BleachBit is released. This is not ideal. The version used by BleachBit has several issues where fixed in the official winapp2 repo months ago, include a bug that will destroy your Visual Studio installation.

With the current approach, the winapp2.ini might as well be bundled into BleachBit. There's no reason for BleachBit to check for updates at all. I suggest BleachBit pull from the official repo instead: https://raw.githubusercontent.com/MoscaDotTo/Winapp2/master/Winapp2.ini

**Comment by az0** [comment]
Good idea. I updated it, though it may take a little while to propagate. Please try it by restarting BleachBit.

A direct copy of the MoscaDotTo version is not ideal because it contains a tiny number of entries that are not compatible with BleachBit 2.0, so I remove them. Also I make some optimizations and perform sanity checks.
