### ISSUE TITLE
%ProgramFiles% in path doesn't work

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#449]
`<action command="delete" search="glob" path="%ProgramFiles%\BiglyBT\*.log"/>`
...doesn't work!

`<action command="delete" search="glob" path="c:\Program Files\BiglyBT\*.log"/>`
...work!

Needed at least for the cleaners of Vuze/Azureus & BiglBT!

**Comment by az0** [comment]
Have you tried `$ProgramFiles` instead of `%ProgramFiles%`?

**Comment by Tobias-B-Besemer** [comment]
Tested it now! Doesn't work!

**Comment by Tobias-B-Besemer** [comment]
Environment Variable %HOMEPATH% also doesn't get resolved!

**Comment by az0** [comment]
In BleachBit, please click **Help - System Information**. Then look for a line that looks like `os.getenv('ProgramFiles')`. Would you please copy the whole line and pastt it here/

**Comment by Tobias-B-Besemer** [comment]
BB v2.1.876:
`os.getenv('ProgramFiles') = C:\Program Files (x86)`
`os.getenv('ProgramW6432') = C:\Program Files`

But if I have a look on this docu... https://en.wikipedia.org/wiki/Environment_variable#Default_values ...it should IMHO look like this:
`os.getenv('ProgramFiles(x86)') = C:\Program Files (x86)`
`os.getenv('ProgramFiles') = C:\Program Files`
`os.getenv('ProgramW6432') = C:\Program Files`

**Comment by Tobias-B-Besemer** [comment]
That are the Environment Variables of my Win7 Cleanup-Machine... Think most of them should be supported... Or I should do a docu on which ones are...

![2019-03-13 03_32_49-Administrator_ C__Windows_system32_cmd exe](https://user-images.githubusercontent.com/11881073/54249658-4ab3d100-4541-11e9-9541-3e43249eb0c8.jpg)

**Comment by az0** [comment]
BleachBit allows all the normal operating system variables, and it adds some extras. 

Windows itself changes `%ProgramFiles%` for 32-bit processes running in a 64-bit operating system as documented here: https://docs.microsoft.com/en-us/windows/desktop/winprog64/wow64-implementation-details

**Comment by az0** [comment]
I would like to close this as a bug. The solution here is to use the `ProgramW6432`, which is defined by Windows itself. This isn't a bug because BleachBit supports all the environment variables provided by Windows.

For compatibility with other Winapp2.ini software, only inside Winapp2.ini BleachBit expands `%ProgramFiles%` to both cases. If you want to log a ticket for a similar enhancement to CleanerML, then you could do that in the wishlist repository. An elegant way to handle this might be a pre-defined multi-value variable called `$$ProgramFiles$$`.
