### ISSUE TITLE
Firefox Error Msg should only appear, if a file was really locked

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#452]
IMHO, the Firefox Error Msg after cleaning should only appear, if a file was really locked - else it just confuses the user.

![2019-02-26 09_01_53-bleachbit](https://user-images.githubusercontent.com/11881073/53396845-cc362b80-39a5-11e9-9e55-a1e9981cdd83.jpg)

**Comment by az0** [comment]
I don't understand "locked." Please explain. 

This error BleachBit detected that Firefox is running, either because the firefox process is running or the Firefox lock file exists in the Firefox profile folder.

BleachBit stops processing any Firefox commands immediately to avoid corrupting Firefox. 

As a reminder to myself, this is the English: "%s cannot be cleaned because it is currently running.  Close it, and try again."

**Comment by Tobias-B-Besemer** [comment]
The junk files I deleted have no affect to the running FF, this was the reason for the issue...
...but WFM!

**Comment by az0** [comment]
Yes, it's true that there may be some files in `firefox.xml`  that are safe to clean while ignoring that Firefox is running, but practically it's hard to identify and mark them, so the safe, easy thing to do is to enforce the policy for all Firefox actions.

Because of this and your "WFM" comment, I close the issue
