### ISSUE TITLE
Issue in resolving path in walk.all?

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#454]
Why does this work:
`<action command="delete" search="walk.all" path="%WINDIR%\Installer\MSI*.tmp*"/>`

And this not:
`<action command="delete" search="walk.all" path="%WINDIR%\*.log"/>`

Because the first one are folders and the second one are files, or is it a bug (e.g. "*" at the beginning) in resolving the path/files?

**Comment by Tobias-B-Besemer** [comment]
`<action command="delete" search="walk.all" path="%SystemDrive%\Boot\BCD.Backup.*"/>`

It's a file, * not at the beginning, also don't work!

**Comment by az0** [comment]
I saw the first action here with MSI*.tmp in your other pull request, and maybe it was working because there was another action with the same `path` but using `search="glob"`. In any case, walk.all is intended to match directories, not files.

The first two cases here (from your first comment) look like they should be search=glob instead of walk.all

Does this answer the question?

**Comment by Tobias-B-Besemer** [comment]
Same for me with walk.files... If this don't work...

`<action command="delete" search="walk.files" path="%ProgramData%\Samsung\Device Error Recovery\default-*.log"/>`

...when does it work ???

**Comment by Tobias-B-Besemer** [comment]
Thx!

**Comment by az0** [comment]
It sounds like this can be closed

**Comment by az0** [comment]
It sounds like this can be closed
