### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#477]
Maybe it's a good idea - as long as I work on the documentation of the CleanerML Syntax - to have a issue open for "Documentation Issues"...

And here is the first question/issue:
I found the following line in google_chome.xml; what do the "?" - is this a space-holder?
`<action command="sqlite.vacuum" search="glob" path="$$profile$$/databases/http*/??"/>`

**Comment by az0** [comment]
Instead of having a giant issue for many documentation issues or documentation issus in general, please let's limit the scope of each issue to something specific

The question mark matches a single character. Please see the [Python glob documentation](https://docs.python.org/2/library/glob.html)

Also, a good place for documentation issues is here https://github.com/bleachbit/docs/issues

**Comment by Tobias-B-Besemer** [comment]
The documentation of the CleanerML Syntax is here:
https://github.com/Tobias-B-Besemer/docs/blob/cleanerml-examples/_posts/cleanerml-examples.md
