### ISSUE TITLE
Installer: "Choose Users" not translated (into German)

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#507]
In the installer, the "Choose Users"-page is not translated at least into German.

![2019-03-25 08_55_48-Installation von BleachBit](https://user-images.githubusercontent.com/11881073/54903865-2d85e780-4edd-11e9-82e7-4c39de6599a3.jpg)

**Comment by az0** [comment]
While I wish I could fix everything, sorry, I personally don't have capacity to fix this. This is the fundamental economic problem: unlimited desires but limited resources. 

This is part of the Windows NSIS installer, so the translation system is separate from what BleachBit normally uses.

If someone can fix this, please open a pull request. Until then, I am closing this because I cannot manage so many open issues. This will help me focus on the highest priority issues. When those are under control, maybe we can revisit this later.

**Comment by Tobias-B-Besemer** [comment]
Andrew, I will try to have a look on it... You can assign me, if you like...

**Comment by Tobias-B-Besemer** [comment]
I made the translation and pushed it as PR https://github.com/bleachbit/bleachbit/pull/518.
As an side effect I pushed PR https://github.com/Drizin/NsisMultiUser/pull/18 in https://github.com/Drizin/NsisMultiUser, too. ;-)
When PR is landed, I will have a look at it and verify, that all looks good...
