### ISSUE TITLE
NSIS silent install does not work in 2.2

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#535]
Reported by MusiqueGraeme [in the forum](https://www.bleachbit.org/forum/silent-install-doesnt-seem-work)

Workaround: revert from BleachBit version 2.2 [to 2.0](https://www.bleachbit.org/download/old)

**Comment by Tobias-B-Besemer** [comment]
Andrew, can you fix the URL?

**Comment by Tobias-B-Besemer** [comment]
This is broken because of integration of NsisMultiUser.
But the command line help and error management is also broken!
This is what I revert as "General Bug Fixes"... ^^
If the user use the following command, it will/should work:
BleachBit-2.2-setup-English.exe /allusers /S
But he can also try one of my builds from here:
https://drive.google.com/drive/folders/1ZbzJimB2rPPaC9zen-5_8frIX5RlCN4M?usp=sharing

**Comment by cihlen** [comment]
I have the same problem but not using the English installer and /allusers /S does not work with the default installer.

**Comment by az0** [comment]
URL fixed

**Comment by Tobias-B-Besemer** [comment]
> The /allusers /S switch also worked with the default installer if I use elevated cmd window. If not already elevated it does not ask for elevation prompt and does not install.

"/S" means "silent"! The installer don't ask, don't talk! ^^

**Comment by Tobias-B-Besemer** [comment]
> Workaround: revert from BleachBit version 2.2 [to 2.0](https://www.bleachbit.org/download/old)

Andrew, the best workaround is to just use the options `/allusers /S`, or `/currentuser /S`. ^^

**Comment by Tobias-B-Besemer** [comment]
Btw.: The title says that it is broken in 2.0, too. ... ^^
