### ISSUE TITLE
Windows: No ASLR and DEP Disabled

### ISSUE THREAD

**Issue by WildByDesign** [bleachbit/bleachbit#546]
I've been using BleachBit for several years yet only realized recently that DEP is disabled and ASLR is not enabled. I noticed this when testing your latest GTK3 build with Dark theme (great job, by the way!). So I decided to test the latest 2.2 stable release as well and noticed also that it was lacking DEP and ASLR.

Is this something that conflicted relating to Python?
Or just something that caused problems with certain functionality?

Anyway, I was just curious. Thank you for your time.

**Comment by az0** [comment]
The platforms and frameworks for BleachBit on Windows (i.e, Python and GTK) are built by the upstream projects, and BleachBit just repackages them, so it it would be up to upstream projects to build the binaries with ASLR and DEP. 

The current roadmap is a focus to update GTK and then Python, and the second part could help. Yet, a quick Google search finds Python [issue 24508](https://bugs.python.org/issue16632) suggesting ASLR and DEP are already in Python 2.7 as of 2015. BleachBit uses a newer Python 2.7. Maybe it has to do with the py2exe freezing tool, which will be replaced during the Python 3 change.

While I agree in general  ASLR and DEP are useful security protections (I remember when they first become popular in Linux), they aren't equally useful in all applications. Applications such as web browsers are a good use case because they interact with a variety of resources (e.g., images) from many sources that can be crafted to crafted to exploit vulnerabilities

BleachBit on the other hand has a small attack surface. If there were a vulernability, it would be difficult for a bad actor to access it. It's rather disconnected from the Internet. Therefore, ASLR and DEP are less useful.

Thoughts?
