### ISSUE TITLE
After cleaning system using Bleachbit, often get "System program problem detected"

### ISSUE THREAD

**Issue by roboirc** [bleachbit/bleachbit#556]
Hi after using Bleachbit, often get "System program problem detected" error and it keeps popping up every boot. I am using Bleachbit (root mode) on Ubuntu 18.04.

Is that normal and if so can we remove the error using as mentioned in this link: 
https://itsfoss.com/how-to-fix-system-program-problem-detected-ubuntu/

Please explain why does this happen only with Bleachbit and whether it is safe or not? Thanks

**Comment by az0** [comment]
Do you notice any problems with the functionality in BleachBit?

If you attach the crash log here, I will take a look.

Which version of BleachBit? If you don't have it, I recommend the latest version (currently 2.2) installed from www.bleachbit.org instead of from the Ubuntu repositories. They often have an old version.

**Comment by roboirc** [comment]
No specific crash log. Just that after using bleach bit to remove stuff often get Crash errors in Ubuntu and I have to clear the errors by clearing the folder /var/crash. But why? Why not make the usage of Bleachbit nice and clean?

**Comment by az0** [comment]
You wrote
>No specific crash log. Just that after using bleach bit to remove stuff often get Crash errors in Ubuntu and I have to clear the errors by clearing the folder /var/crash. 

At this point there is not enough information for me to do anything because I can't reproduce the problem on my system, and from your description I can't isolate the problem. It would help to have more specifics---maybe a screenshot of the crash. 

Perhaps you can find a crash log in /var/crash with more information. This would probably be the most helpful. If you can, please upload it here.

You wrote
>Why not make the usage of Bleachbit nice and clean?

You ask as if the crash were intentional. Of course it's not intentional. Also, your problem is relatively rare, so I would say, in general, usage of BleachBit _is_ "nice and clean."

Earlier I asked a question to help me isolate your problem, but  I didn't see an answer. Here is the question again

>Which version of BleachBit? If you don't have it, I recommend the latest version (currently 2.2) installed from www.bleachbit.org instead of from the Ubuntu repositories. They often have an old version.

**Comment by az0** [comment]
No response to question from May 2019, so I am closing the issue. If you want to continue the discussion, just add a comment to this issue.
