### ISSUE TITLE
NameError: global name '_' is not defined when cleaning TeamViewer

### ISSUE THREAD

**Issue by beeriz** [bleachbit/bleachbit#559]
Here's the screenshot from the error with the debug console open.

![image](https://user-images.githubusercontent.com/13268158/58368006-60992700-7ede-11e9-83db-f862edc60ed8.png)

any idea what's causing this?

**Comment by az0** [comment]
Thanks fo the report.

This is a duplicate of https://github.com/bleachbit/bleachbit/issues/508

The cause is a bug related to printing the debugging message that a directory is not empty. The error is basically harmless.

It is fixed, and you can preview the latest release (with the fix) here https://ci.bleachbit.org/ . There have been many other changes too

**Comment by az0** [comment]
You could test this fix in the newly-released [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta)
