### ISSUE TITLE
update progs not detecting correct Bleachbit version number

### ISSUE THREAD

**Issue by astro46** [bleachbit/bleachbit#597]
Have had this issue with different update programs.  they all think that I have Bleachbit 2.0 installed and want to update to 2.2.   In fact I already have 2.2 installed.  And have tried re-installing it several times.

**Comment by az0** [comment]
What are the names of the update programs?

**Comment by astro46** [comment]
the two that come to mind from most recently are filehippo (the standalone 1.47 ver  https://filehippo.com/download_app_manager/59899/   and Patch My PC updater free  https://patchmypc.com/home-updater-download

**Comment by az0** [comment]
I tried Filehippo 1.47 and 2.0 beta 4, and each failed to work at all in different ways.

If you look in Windows Control panel under Add/Remove Programs, it shows a list of installed programs. BleachBit shows correctly as version 2.2.

Then if you right click on the `bleachbit.exe` file that is installed under c:\program files(x86)\bleachbit\, click Properties, and click Details, then the correct version 2.2 shows there too.

For these two reasons I think the update apps seem to be out of date, and BleachBit itself isn't doing anything weird or wrong. I suggest filing a ticket with the vendors of those update applications. If they have anything constructive to add, I would listen, but otherwise I think it's up to them to change their apps, so I will close the issue

**Comment by astro46** [comment]
Patch My PC was also showing ver 2 installed and wanting to update to 2.2.

 

However your comment about add/remove programs showing 2.2 installed, lead me to open IObit uninstaller, and Revo Uninstaller, both of which showed BB 2.2 and BB 2.0 installed.  I uninstalled 2.O and ran 2.2 install again.  

 

Now Patch My PC is not asking for update to BB 2.2.

 

Seems the issue came from BB not fully uninstalling 2.0 when updating to 2.2.  Or correcting a reg entry, or whatever it is supposed to do when updating.

 

Nevertheless, thanks for providing  a very useful program. 

 

Jeffrey
