### ISSUE TITLE
Many Files Not Removed

### ISSUE THREAD

**Issue by diny13601** [bleachbit/bleachbit#599]
BleachBit Version 2.2
OS: Windows 10 Home (x64) Version 1809 (build 17763.615)
No error message. The problem is that if I run other disk clean programs after BleachBit, I still have many files which the other programs remove. 

I use Glarysoft - Glary Utilities version 5.10.0.1, IObit - Advanced SystemCare version 12.4.0, Advanced System Care 12.4 Free, Ashampoo WinOptimizer 2019 No Version No., Wise Disk Cleaner Version 10.2.3.774, CCleaner Version 5.60.7307 (64-bit).

![CC Cleaner](https://user-images.githubusercontent.com/48453618/62421665-68f6a680-b673-11e9-9aca-1407e4943a4f.png)
![Wise Disk Cleaner 2](https://user-images.githubusercontent.com/48453618/62421666-68f6a680-b673-11e9-9f88-670279f4d5a4.png)
![Wise Disk Cleaner](https://user-images.githubusercontent.com/48453618/62421667-68f6a680-b673-11e9-93e9-97b0e8a92180.png)
![WinOptimizer 2](https://user-images.githubusercontent.com/48453618/62421668-698f3d00-b673-11e9-9258-50423f76cd69.png)
![WinOptimizer](https://user-images.githubusercontent.com/48453618/62421669-698f3d00-b673-11e9-8f88-e285c398d46e.png)
![Iobit Disk Clean 2](https://user-images.githubusercontent.com/48453618/62421670-698f3d00-b673-11e9-815c-54cd1039b05a.png)
![Iobit Disk Clean](https://user-images.githubusercontent.com/48453618/62421671-698f3d00-b673-11e9-8dff-3e453a1d08d7.png)
![Glary Disk Cleanup](https://user-images.githubusercontent.com/48453618/62421672-6a27d380-b673-11e9-90c8-b7b6a3813b20.png)
![CC Cleaner 2](https://user-images.githubusercontent.com/48453618/62421673-6a27d380-b673-11e9-8b00-1a8606c2bba2.png)

**Comment by 2635599** [comment]
you do know you should of listed what cleaners in bleachbit you have checked, and what files it's not cleaning.  none of those images were even remotely necessary.

**Comment by az0** [comment]
@diny13601  
Thanks for your ideas. I understand where you are coming from, but the scope of this issue is broad and unclear, so it is difficult to exactly fix. For example, if I were to make BleachBit clean 15 more things, I am not sure that would cover everything you described. Also, I would like to avoid just copying and pasting rules from other applications.

Ideally you could help contribute solutions by enhancing the cleaning rules using [CleanerML](https://docs.bleachbit.org/cml/cleanerml.html). For example, if some files in Firefox are not cleaned, then you would edit `firefox.xml` and submit your changes back here using a GitHub pull request.

The second best thing is to open an issue ticket that is more specific. For example, the ticket could be called "Five files not cleaned for Firefox", and then you could list the five specific files all along with your Firefox version number. (I see you listed your Windows version number, so thanks for that.) 

If submitting a ticket for Firefox, be sure to use all the Firefox options to make sure BleachBit doesn't already clean them. On Windows, BleachBit has extra cleaning rules for Firefox if you enable the Winapp2.ini system in the Preferences.

I am using Firefox as an example, by the way.
