### ISSUE TITLE
BB still hangs during start by caching system

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#676]
As reported before in an other bug, BB (still) hangs during start by caching the system.
If I close BB and restart it, all works well ('cause system is already cached).
I think this should be changed in at least this way, that BB hangs not complete and Windows and the user don't think that BB wont works no more.

![2019-11-06 04_42_29-Ressourcenmonitor](https://user-images.githubusercontent.com/11881073/68270278-1c997900-005d-11ea-83d7-d6c3629ea872.jpg)

**Comment by Tobias-B-Besemer** [comment]
To see in the SS: BleachBit is marked red in the resources monitor!

**Comment by az0** [comment]
You mean the first start of the application takes a long time, or it never finishes? This sounds like an issue of using the disk, though the screenshot shows the CPU usage instead of the disk.

**Comment by Tobias-B-Besemer** [comment]
It takes a long time, but this is not the prob! The prob is, that "the prog gets reported a unusable" to windows! You see in the SS BB marked as red on the left side... Red means that the prog is no more able to communicate with Windows/don't react to Windows requests anymore.

**Comment by mkhon** [comment]
@az0 @Tobias-B-Besemer In my Windows VM if bleachbit is started without %LOCALAPPDATA%/fontconfig directory (no fontconfig cache) it takes several minutes to build the cache.

**Comment by az0** [comment]
@mkhon 
Good observation. I tested in my Windows VM. Without the fontconfig cache, it took about 40 seconds. With the cache, it was almost instant.

The worst part is the user gets no visual feedback in the GUI to explain what is happening.

I wonder if there is either a way to speed up the fontconfig process.

**Comment by rados** [comment]
@az0 I could reproduce it and can investigate further.

**Comment by rados** [comment]
@az0
My research till now points that we can call "fc-cache.exe" from the installer and this way generate the font cache during installation. I tried it manually and it works. But if the user deletes the cache somehow then on the first run after the deletion the Bleachbit app will re-create the cache and wait as it does currently. But this should be a rare case. If we want to handle it than we can think of a more complex solution.

**Comment by az0** [comment]
@rados 
I like the idea of calling it from the NSIS installer. Can you execute it after the end of the "core" section? Do you need to check for whether the cache already exists to avoid re-building it, when run a second time?

**Comment by az0** [comment]
In the screenshot BleachBit log shows
>Rufen Sie das Anwendungsmenü auf, indem Sie auf das Logo in der Titelleiste klicken
Which means "Access the application menu by clicking the logo on the title bar"

BleachBit progress bar shows
>laden von naiven cleanem
Which means "loading naive cleaners"

Task manager shows
>physikalischer speicher 83%
Meaning "physical memory 83%"

Memory is mostly full but it does not seem like much paging

Earlier Tobias wrote
>The prob is, that "the prog gets reported a unusable" to Windows! You see in the SS BB marked as red on the left side... Red means that the prog is no more able to communicate with Windows/don't react to Windows requests anymore.

So I think Tobias's issue is that the process of loading native cleaners happens in the same process as the GUI, and it can cause the GUI to become unresponsive.

@Tobias-B-Besemer  
Could you troubleshoot by unchecking the preference checkbox "Hide irrelevant cleaners"? If this speeds it up, we know the issue is in the auto-hiding process.

For future troubleshooting, we could also add code to sum all the durations spent in `auto_hide()` function as called from `refresh_rows()` function. If the duration is long, it could be logged as a warning like "X seconds were spent checking which cleaners to hide."

@rados 
Looking back at this Tobias's issue, I think it can't be the font caching because I think that would happen  before the application GUI launches, but in the screenshot, the GUI already started. Addressing the slowness of font caching is still worth pursuing, but how about you create a new ticket for that? Some relevant questions are

1. Are there cases where fc-cache fails to cache, so it tries to cache every time the application starts.
2. Can the caching be avoided altogether because we need only certain fonts
3. Can we give the user visual feedback that caching is in progress
4. Can we run fc-cache from the installer without causing problems for special cases such as multi-user systems and silent installation mode

**Comment by az0** [comment]
>  I could reproduce it and can investigate further.

@rados 

Can you reproduce this after the application has started? (This is not the font cache issue because that happened before the GUI showed up, and in his screenshot, the GUI has started.)

**Comment by rados** [comment]
> > I could reproduce it and can investigate further.
> 
> @rados
> 
> Can you reproduce this after the application has started? (This is not the font cache issue because that happened before the GUI showed up, and in his screenshot, the GUI has started.)

Not really, I will live the issue unassigned for now as I don't have an idea what the reason could be.

**Comment by az0** [comment]
We cannot reproduce the issue. Because I haven't heard from Tobias here or elsewhere since January 2020, I will close the issue. 

@Tobias-B-Besemer  
If you can reproduce with a recent version of BleachBit, please reopen.
