### ISSUE TITLE
Bleachbit should not have deleted ssh-askpass used to integrate my VS Code & GitHub in Ubuntu 19.10.

### ISSUE THREAD

**Issue by PranavBhattarai** [bleachbit/bleachbit#731]
This is what I get everytime I try to push updates to my Git repo. Bleachbit is creating the problem. 
Enlighten me if I am wrong.
![Screenshot from 2019-12-12 12-00-25](https://user-images.githubusercontent.com/32763112/70687642-e09aa900-1cd7-11ea-97ab-6e526db5c5e3.png)

**Comment by az0** [comment]
You think BleachBIt deleted `/usr/bin/ssh-askpass`? I am not aware of any rule that deletes anything under `/usr`. Which options did you have checked?

**Comment by PranavBhattarai** [comment]
@az0 Distribution is mentioned in the issue title (Ubuntu 19.10). BleachBit version: 3.0
You mean Bleachbit don't touch "/usr" directory? Is there no chance it could have deleted those? If its the truth then my bad. Because I don't remember deleting it, so. Only delete things are done by Bleachbit since I use it. So I asked here.

**Comment by az0** [comment]
@PranavBhattarai 
With the built-in cleaners, there are no cleaners that reference `/usr/bin`. (You can check by running grep on the .xml files under the `cleaners` directory.)

There is an option to run APT autoremove. This can remove packages, but this doesn't seem like a package that would be removed. If you think this is the case, check whether the package is installed.

I'm not familiar with askpass, but I did a search for the missing command. There were two hits on Ubuntu 19.04
```
$ apt-file find /usr/bin/ssh-askpass 
ssh-agent-filter: /usr/bin/ssh-askpass-noinput
ssh-askpass-fullscreen: /usr/bin/ssh-askpass-fullscreen
```
Neither file is identical to what you have, so I wonder whether there is a misconfiguration instead of a missing file. I suggest a [Google search for the error message](https://www.google.com/search?q=git+ssh-askpass+%22no+such+file%22). Let me know what you find.

**Comment by PranavBhattarai** [comment]
The commands u mentioned have no effect.
```
pranav@Exam:~$ apt-file find /usr/bin/ssh-askpass
pranav@Exam:~$ apt-file find /usr/bin/ssh-askpass-noinput
pranav@Exam:~$ apt-file find /usr/bin/ssh-askpass-fullscreeen
```
The project holder was in the home directory which had all required ssh keys & permission. And I think Bleach delete those credential files and this is happening.

**Comment by PranavBhattarai** [comment]
@az0 the problem is solved. I did a stupid mistake by myself as explained here.

And I forget that I created this issue. **Sorry to blame bleach-bit**. And thanks for ur replies.
