### ISSUE TITLE
Bugs in Mint 19.3

### ISSUE THREAD

**Issue by Linux-Johnston** [bleachbit/bleachbit#739]
Dark mode and automatic search for updates do not work in Bleachbit for Mint 19.3 Tricia.

**Comment by az0** [comment]
1. Did you install BleachBit from the .deb package at www.bleachbit.org , from Mint's repository, from source, or some other way ?
2. Is it BleachBit version 3.0 or another version?
4. What happens wen you toggle the dark mode option?
5. Is there a checkbox to search for updates? How do you know it doesn't work?

Also, please follow separate tickets for separate bugs to make it easier to manage them. These seem to be two unrelated issues.

**Comment by Linux-Johnston** [comment]
1. Yes, I directly installed it from your web site bleachbit.org.
2. It is version 3.0
3. Nothing happens. Surface stays in light mode, dark mode is confirmed though.
4. When I started BleachBit as Administrator a window popped up, saying the program was unable to search for updates.

**Comment by az0** [comment]
You wrote:
>When I started BleachBit as Administrator a window popped up, saying the program was unable to search for updates.

Please provide the verbatim error message by either pasting it or by adding a screenshot.

You also write
>Nothing happens. Surface stays in light mode, dark mode is confirmed though.

Hmm. Are you using Gnome as a desktop manager? Do you have the default Gnome/GTK theme (the default for Linux Mint 19.3)? It's possible this theme doesn't have a dark version. 

Let me know, and I will research more.

I am closing because there are two issues in one ticket, and this makes it hard to manage either. Please open a new ticket for each.
