### ISSUE TITLE
Linux Mint 19.3 Tricia: Code 9 

### ISSUE THREAD

**Issue by Linux-Johnston** [bleachbit/bleachbit#742]
I'm receiving this error information when running BleachBit as administrator in Linux Mint Tricia:

Der Kind-Speicher-Reinigung-Prozess gab Code 9 zurück.

**Comment by az0** [comment]
English translation (from Google): "The child memory cleaning process returned code 9."

@Linux-Johnston 
1. Which version of BleachBit?

2. Would you please run BleachBit from a terminal _or_  with the debug logging option enabled in the preferences. (The preference requires BleachBit 3.0 or later.)  This logging could give us more information. In case there is more information, please copy and paste it here.

**Comment by az0** [comment]
There was no response for one year, so I am closing this issue. If you want to continue this discussion, feel free to add a comment to this issue.

**Comment by jonas-w** [comment]
Sorry for opening it again. But I've had this error on every pc and distribution i used this tool. Never bothered about it. But today i wanted to check what that error means i get all the time. Feel free to ask for further details.

**Comment by jonas-w** [comment]
> Okay i think it's not an error. The bug is that the error gets displayed.
https://github.com/bleachbit/bleachbit/blob/76e0ed2dc707607cadb0bfcb2533a46c96ae9bd7/bleachbit/Memory.py#L324 

I think the child process gets killed because it's using too much memory. Makes sense it allocates all free memory. It get's killed with the SIGINT Signal from the system for using too much memory. The check for that error should be rewritten.

**Comment by jonas-w** [comment]
Correct me if I'm wrong!
