### ISSUE TITLE
MSVCR100.dll error with build 1490 (Python 3)

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#758]
I downloaded this build: https://ci.appveyor.com/project/az0/bleachbit/builds/30331642/artifacts

Then, I installed on Windows 10

It gave me a MSVCR100.dll error 

![dll error](https://user-images.githubusercontent.com/933680/73127633-7b95cc80-3f80-11ea-8b96-7bbd06071588.png)

**Comment by mkhon** [comment]
This has been fixed in the new python3 PR. However I am not sure we are allowed to redistribute this copy of msvcr100.dll.

Including vcredist_x86.exe into the installer (and running it during the installation) looks more legal but it will not work for portable version.

Probably more proper (long-term) way to fix this is to rebuild py2exe so that it is uses static runtime.
