### ISSUE TITLE
Opera doesn't seem to be cleaned up

### ISSUE THREAD

**Issue by reams** [bleachbit/bleachbit#764]
There is no indication about the memory released, as in the browser itself, to be fair...

BleachBit 2.0 on Ubuntu 18.04

**Comment by az0** [comment]
BleachBit 2.0 is old. [BleachBit 2.2](https://www.bleachbit.org/news/bleachbit-22) released March 2019 fixed this bug. Since then, BleachBit 3.0 final and 3.1 beta were released too. 

Ubuntu has a "no rolling release" policy, so they don't update BleachBit except for new versions of Ubuntu. That means Ubuntu is often behind, so I highly recommend installing bleachbit from the www.bleachbit.org site.
