### ISSUE TITLE
Thumbnails and Clipboard aren't deleted after a run [Windows]

### ISSUE THREAD

**Issue by Nicholas1488** [bleachbit/bleachbit#772]
To be exact its thumbcache_96.db (C:\Users\USERNAME\AppData\Local\Microsoft\Windows\Explorer) that isn't deleted, all other thumbnail related files are cleared. The clipboard simply just has it the old contents saved.

**Comment by az0** [comment]
Which version of BleachBit are you using?

Are there any red error messages in the BleachBit log window?

**Comment by Nicholas1488** [comment]
BleachBit version 3.0

No, it just said it's done.

**Comment by az0** [comment]
I added the clipboard problem to the [BleachBit 3.0 known issues](https://www.bleachbit.org/news/bleachbit-30#known). See the solution there.

About thumbnails, please uncheck all options except Windows Explorer - Thumbnails, run delete, copy the information from the log window, and paste it here.  I am wondering what else it shows.

**Comment by az0** [comment]
I am closing because

1. [BleachBit 3.2.0 final](https://www.bleachbit.org/news/bleachbit-320) was released with the fix for the clipboard.
2. No response about the thumbnails
3. Each issue ticket should be about one issue, but this ticket is about two things

If you still have problems with either clipboard or thumbnails, please open a new ticket (one ticket per issue).
