### ISSUE TITLE
Doesn't Install in Fedora 32 (Dependency Problem)

### ISSUE THREAD

**Issue by hhlp** [bleachbit/bleachbit#813]
Error: 
 Problem: conflicting requests
  - nothing provides python2-chardet needed by bleachbit-3.2.0-1.1.noarch
  - nothing provides python2-gobject needed by bleachbit-3.2.0-1.1.noarch
  - nothing provides python2-scandir needed by bleachbit-3.2.0-1.1.noarch

Regards.,

**Comment by az0** [comment]
Would you try BleachBit 3.9.0 alpha? It updates BleachBit to work with Python 3 instead of Python 2, and it also includes fixes for issues just like yours.

You can get an RPM from [OpenSUSE Build Service](https://software.opensuse.org//download.html?project=home%3Aandrew_z&package=bleachbit). Choose **Fedora** and then Grab Package Directly.

**Comment by hhlp** [comment]
Done thx without no issues
