### ISSUE TITLE
Cleaners: limit actions to OS

### ISSUE THREAD

**Issue by cfoellmann** [bleachbit/bleachbit#84]
I encountered following issue. Example:
Virtualbox is available for Win and Linux.

``` xml
<cleaner id="virtualbox">
  <label>VirtualBox</label>
  <description>Virtual machine</description>
  <option id="logs">
    <label>Logs</label>
    <description>Delete the logs</description>
    <action command="delete" search="walk.all" path="$USERPROFILE\.VirtualBox\" regex="\w+\.log(\.\d+)$"/>
    <action command="delete" search="walk.all" path="~/.VirtualBox/" regex="\.log(\.[0-9]+)?$"/>
    <!-- Chakra 2014.02 has ~/.config/VirtualBox -->
    <action command="delete" search="walk.all" path="~/.config/VirtualBox/" regex="\.log(\.[0-9]+)?$"/>
  </option>
</cleaner>
```

I know that these delete actions are a little different but produce duplicate results.
`path="~/.VirtualBox/"` shouldn't even be run on Windows but both actions run and files are found with `/` and `\` as path delimiters.

I thought a solution could be to separate win/linux cleaners by setting `<cleaner id="virtualbox" os="windows">` and `<cleaner id="virtualbox" os="linux">`.
But if I do that and both files are in the cleaners folder (on Windows) both actions are run. Resulting in the same issue.

**Comment by tiemay** [comment]
> I thought a solution could be to separate win/linux cleaners by setting `<cleaner id="virtualbox" os="windows">` and `<cleaner id="virtualbox" os="linux">`.
But if I do that and both files are in the cleaners folder (on Windows) both actions are run. Resulting in the same issue.

I imagine having multiple cleaners with the same id could be problematic. Also, I'm not sure if using Linux paths on windows is intentional or not. The [documentation](http://bleachbit.sourceforge.net/contribute/cleaner) under "Testing the cleaner" says to never use `~` in windows. Yet, the gimp cleaner uses it and otherwise wouldn't currently be working on windows. A clarification on this matter has been requested in [launchpad #1366662](https://bugs.launchpad.net/bleachbit/+bug/1366662). Until this behaviour is clarified, I wouldn't make or accept any pull requests related to this issue; You're proposing a pretty big change to how cleaners are written when it might just be a simple bug that lets `~` or `/` be used on windows.

If we are going to separate actions based on os though, I suggest something like this:
```
<cleaner id="foo">
  <label>bar</label>
  <description>baz</description>
  <option id="logs">
    <label>Logs</label>
    <description>Delete the logs</description>
    <group os="linux">
      <action command="delete" search="walk.files" path="..."/>
      <action command="delete" search="walk.files" path="..."/>
    </group>
    <group os="windows">
      <action command="delete" search="walk.files" path="..."/>
      <action command="delete" search="walk.files" path="..."/>
    </group>
  </option>
</cleaner>
```
This way the cleaner id, label, descriptions, and option id's are all reused keeping the code [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself)er, and we wouldn't need to create a new cleaner.xml file for each os.

I'd like to hear @az0's take on this though.

**Comment by az0** [comment]
In general specifying a path for the operating system (e.g., such as `~/.config/..` on Windows) is harmless because it does not exist. There is a tiny performance penalty checking whether the file exists. This is how things have worked so far. 

Recent commits have added multi-value variables that support the DRY principle that @tiemay mentioned.

Still, I'll add a os= option for action.
