### ISSUE TITLE
Bleachbit arrow tab missing 

### ISSUE THREAD

**Issue by silentshotghost** [bleachbit/bleachbit#853]
Menu tabs are missing https://imgur.com/a/lnnLGbV

BleachBit version 3.2.0
Build number 1509

**Comment by az0** [comment]
If in the preferences you disable the dark theme, do the arrows appear?

**Comment by ediowar** [comment]
![No arrows](https://user-images.githubusercontent.com/44164186/78728034-ce4b1780-7925-11ea-8baf-2216e225ce35.png)

**Comment by silentshotghost** [comment]
dark mode doesn't affect it https://imgur.com/a/VLaxPZl

**Comment by az0** [comment]
What happens if you check the checkbox?  For example, in @ediowar 's screenshot, there is Firefox without the arrow. If Firefox is checked, does the preview show any items from Firefox?

Is the arrow many invisible? What I mean is: try clicking where the arrow should be, and check whether it expands.

My guess is they are not invisible: it seems like some cleaners (e.g., Firefox) are missing options (e.g., cache, cookies).

**Comment by silentshotghost** [comment]
https://imgur.com/a/DleJG5a

https://a.cockfile.com/vnaIsQ_2020-04-07_18-12-58.gif

**Comment by mkhon** [comment]
I also see this in portable build.

**Comment by ediowar** [comment]
![no arrows 2](https://user-images.githubusercontent.com/44164186/78790570-405f4300-799e-11ea-9915-2730c2678579.png)

**Comment by az0** [comment]
Max added a missing icon
