### ISSUE TITLE
No native CleanerML files to load when checking winapp2.ini in Preferences

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#861]
In the first running, after the winapp2.ini checking in Preferences, native CleanerML files loads. Further in other runnings it does not load. To load CleanerML files just for one running, you need to delete cleaners folder BleachBit-Portable\cleaners.
![No CleanerML](https://user-images.githubusercontent.com/44164186/78995859-d3c97d00-7b32-11ea-8158-e0e062fe87a6.png)
```
BleachBit version 3.9.1
Build number 1622
local_cleaners_dir = C:\downloads\BleachBit-Portable\cleaners
personal_cleaners_dir = C:\downloads\BleachBit-Portable\cleaners
system_cleaners_dir = C:\downloads\BleachBit-Portable\cleaners
```

**Comment by az0** [comment]
Yes, confirmed. Thank you

**Comment by az0** [comment]
Starting from a clean configuration in portable mode, the first time the application starts the variables are these

```
local_cleaners_dir = c:\BleachBit-Portable\cleaners
system_cleaners_dir = c:\BleachBit-Portable\share\cleaners\
```

Then I enable the Winapp2.ini preference and restart the application. The values are the same.

The third time I start the application, the values changed

```
local_cleaners_dir = c:\BleachBit-Portable\cleaners
system_cleaners_dir = c:\BleachBit-Portable\cleaners
```

The problem is the systems cleaners directory changed.
