### ISSUE TITLE
Wanting to help!

### ISSUE THREAD

**Issue by dr-ss** [bleachbit/bleachbit#885]
Howdy,

I'd like to help out this project and don't know how else to do this. Can we get in contact via email (somehow) and work on doing some beta testing? I have a Citrix XenServer build with the following:

Ubuntu (latest if needed)
Linux Mint (latest if needed)
Windows 2012 R2 ISO
Time is available...

See tech-idea.com (blog for more background).

Thanks!

**Comment by az0** [comment]
When I release beta versions (example: [3.9.2](https://www.bleachbit.org/news/bleachbit-392-beta)), I write areas of focus for testing. 

There is also an [article on testing](https://www.bleachbit.org/contribute/testing). (The article is older, so let me know if something needs updated or explained.)

Another way to test is just to use the software like you would normally. When you notice a problem, report the bug here on GitHub.

Does this help you get started? If so, close the issue.

**Comment by dr-ss** [comment]
I'll keep this open a few more days while I poke around right quick. This way I can ask a question if I run into something. My apologies for the latent reply.

Thanks!

**Comment by dr-ss** [comment]
Closing this out, sorry for leaving this open for so long.
