### ISSUE TITLE
After using bleachbit with root no more discspace is available (4.0.0.1)

### ISSUE THREAD

**Issue by katasta** [bleachbit/bleachbit#892]
Hey guys.
I did learn not to use blechbit with root. After the action i did read about some issues. Won't do it again. But it happens;)

Now: The phenomenon is that no more free space is sent to the manjaro system even though the disk analysis shows free space. So I can't install an update anymore. When I uninstall a program NO free space is generated.

Unfortunately I uninstalled bleachbit, but since then I can't install it anymore.

Does anyone have any idea which option I may have unknowingly activated and how I can solve this problem again? The system is running, I haven't noticed any other problems. 

I did not stop any process while running bleachbit. I have the feeling that i had to refresh the keys of the server (perhaps i did advice bleachbit to do so).

so i did sudo pacman-key --refresh-keys, sudo pacman-key --init and udo pacman-key --populate archlinux because it fails.

Thank you, guys!

**Comment by ediowar** [comment]
[Q: I closed BleachBit while it was working for a long time, and now my hard drive is full. How do I fix it?](https://docs.bleachbit.org/doc/frequently-asked-questions.html)

**Comment by az0** [comment]
> Unfortunately I uninstalled bleachbit, but since then I can't install it anymore.

To add on to what ediowar wrote, you can try this command to look BleachBit's large files that apparently it wasn't able to clean because it was shutdown prematurely. Not all huge files were created by BleachBit. The files it created have very long names made of random characters.

`find / -type f -size +1G`

**Comment by ediowar** [comment]
> @az0 [incorrect link](https://docs.bleachbit.org/documentation/shred-files-wipe-disk) in Q: Why does BleachBit take a long time (more than five minutes) while filling up by hard drive?

At https://docs.bleachbit.org/doc/frequently-asked-questions.html the answer to the question: Why does BleachBit take a long time (more than five minutes) while filling up by hard drive? contains link `https://docs.bleachbit.org/documentation/shred-files-wipe-disk` instead of `https://docs.bleachbit.org/doc/shred-files-and-wipe-disks.html`.

**Comment by az0** [comment]
@ediowar 
Thanks, I fixed the link. (If you do not see it now, refresh the page.)
