### ISSUE TITLE
Duplicate issues

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#916]
To avoid duplicate issues, I propose add the text at https://www.bleachbit.org/help
Ask a question on [GitHub](https://github.com/bleachbit/bleachbit/issues/new) **after searching for a similar issue [bleachbit issues](https://github.com/bleachbit/bleachbit/issues)**

**Comment by az0** [comment]
A long time ago, duplicate issues used to bother me, and I'd combine them. Lately, I prefer each user to report the issue individually for a few reasons

1. It shows the bug is important, if more people report it
2. Sometimes what looks like a duplicate might be a separate issue
3. During the diagnosis and confirmation, separate issues keep the conversations separate and easier to read.

What do you think?

**Comment by ediowar** [comment]
I agree.
