### ISSUE TITLE
error cleanning

### ISSUE THREAD

**Issue by pizarrocz** [bleachbit/bleachbit#945]
hi, when i only have one ssd the program it work just fine, but now i have an ssd and hdd and it dosent work well, dosent clean all the files can anybody help me

![error](https://user-images.githubusercontent.com/66091627/84672993-0d4aaa00-af21-11ea-8962-55664343ce27.png)

**Comment by pizarrocz** [comment]
i think i found the solution its just go settings and remove the other hard (units) drives, can anybody verify my problem?

**Comment by az0** [comment]
Earlier did you non-removable have  D: and E: drives?  If they existed when you first started BleachBit for the first time, it would have set them up for wiping when the "free disk space" option was run. However, it does not automatically remove these options later when the drives are removed, so that would explain the error. You fixed it by adjusting the preferences.

Does this help?

**Comment by az0** [comment]
I am closing because of no reply since my message 229 days ago
