### ISSUE TITLE
Theme Option Setting and Language Preferences

### ISSUE THREAD

**Issue by realagentwhite** [bleachbit/bleachbit#946]
I've been trying to figure a way to add a configuration that would allow a user to change the language of bleachbit after installation meaning that the program will install as usual but have an option in preferences to change to another.

Also, I thought it would be a good idea to have an option (if not hard to do) to be able to change themes. For example, say you want to use the theme from version 2.0, there could be an option to have **classic theme** or **default theme**. I've been trying to see if I can get that to work as well but no success.

**Comment by az0** [comment]
> I've been trying to figure a way to add a configuration that would allow a user to change the language of bleachbit after installation meaning that the program will install as usual but have an option in preferences to change to another.

Assuming you are on Windows, please [see the FAQ](https://docs.bleachbit.org/doc/frequently-asked-questions.html#q-how-do-i-see-bleachbit-in-my-own-language-on-microsoft-windows)

Q: How do I see BleachBit in my own language on Microsoft Windows?
A: There are a few ways to affect the language of the BleachBit user interface.

In the Windows search bar, type “Language settings” and open it. Under the Windows display language, choose the preferred language, and then restart BleachBit.

To force BleachBit to always show in English, download and install the English installer instead of the regular installer. If using the regular (non-English-only) installer, uncheck the option to install translations.

The language chosen in the BleachBit installer does not affect the BleachBit application: it affects only the language of the installer.

> Also, I thought it would be a good idea to have an option (if not hard to do) to be able to change themes. For example, say you want to use the theme from version 2.0, there could be an option to have **classic theme** or **default theme**. I've been trying to see if I can get that to work as well but no success.

Please do not file unrelated issues in one ticket. It makes it difficult to manage. In BleachBit 4.0 on Windows, you can choose from four themes via the BleachBit preferences. On Linux, BleachBit uses the system theme with an option for dark mode.
