### ISSUE TITLE
Is this true? 'There is no way to securely delete files on modern filesystems, and/or on SSDs.'

### ISSUE THREAD

**Issue by NicodemusArchleone** [bleachbit/bleachbit#963]
I recently switched to Pop!_OS from Windows and when I was using Windows there were programs to automatically erase content with overpasses such as CCleaner and Hardwipe. I posted on a Pop! related forum asking about Bleachbit's shred and overwrite function and received this in response:

> There is no way to securely delete files on modern filesystems, and/or on SSDs. Using an encrypted filesystem (or putting the filesystem on an encrypted block device) is the only way to prevent possible recovery of deleted files.

Is this correct? I suspect it to be BS....

I could also use some advice on using Bleachbit in Pop/Ubuntu correctly.

**Comment by az0** [comment]
>There is no way to securely delete files on modern filesystems, and/or on SSDs. 
Please see the document [Shred files and wipe disks](https://docs.bleachbit.org/doc/shred-files-and-wipe-disks.html).

>Using an encrypted filesystem (or putting the filesystem on an encrypted block device) is the only way to prevent possible recovery of deleted files.

Encryption certainly helps.


>I could also use some advice on using Bleachbit in Pop/Ubuntu correctly.


In what way?

**Comment by chvol** [comment]
Correct: with modern operating systems you have no control over which sectors (= exact physical location on hard disk/SSD) are being written to. You might "overwrite" a file, but that could mean that the current sectors are deallocated and new ones written to), this is certainly true with copy on write mechanisms. This means that the old data is still somewhere on your disk, there just isn't a pointer to it.

SSD's make this even "worse" since they do wear leveling in order to increase life span: you have no control over which cells the data will be written to and in order to change a single cell, you have to erase and rewrite an entire block. So writing to an SSD may mean writing to an entire new block and marking the old one for recycling, so theoretically you could have multiple versions of your file on the SSD. Add over-provisioning to this (your SSD has more space than it says it has, to increase lifespan. Just as the battery of an electric car has more capacity than advertised) and you can't even be sure that you completely deleted your data by filling all available space with random data (which, by the way, is a good way of reducing the lifespan of an SSD).

Only 2 ways to be sure your data cannot be read back from disk/SSD:
- encryption
- physical destruction of the medium (not as easy as it sounds, look up some extreme data recovery stories)

**Comment by az0** [comment]
> Just as the battery of an electric car has more capacity than advertised) and you can't even be sure that you completely deleted your data by filling all available space with random data 

OK, but you can be mostly sure it is gone if the available space is filled up, especially if the data you want deleted is large. Also, it is not easy to directly access the lower level storage of the SSD (beyond what it shows the operating system), so anyone accessing the SSD in a normal way would see the data was completely deleted. 


>(which, by the way, is a good way of reducing the lifespan of an SSD).

I agree that people shouldn't be careless with the lifespan of an SSD, but a 2016 Google study found that SSDs have life spans longer than those of HDDs. 

>Only 2 ways to be sure your data cannot be read back from disk/SSD:
>encryption
>physical destruction of the medium (not as easy as it sounds, look up some extreme data recovery stories)

Yes, those are the most reliable methods for anyone who is willing to pay the costs of the highest-level security.

As the article states, there are tradeoffs that each person must make between costs/convenience and security.


Are we OK to close this issue?

**Comment by chvol** [comment]
> OK, but you can be mostly sure it is gone if the available space is filled up, especially if the data you want deleted is large. Also, it is not easy to directly access the lower level storage of the SSD (beyond what it shows the operating system), so anyone accessing the SSD in a normal way would see the data was completely deleted.

With large data, I'd think you'd have a larger chance of finding parts of it, which may or may not be a problem. Of course it's not easy to directly access the low level storage of an SSD, but for completeness I wanted to address over-provisioning and it's possible impact for security.
 
> I agree that people shouldn't be careless with the lifespan of an SSD, but a 2016 Google study found that SSDs have life spans longer than those of HDDs.

In normal use I agree, but if you are repeatedly overwriting all available space, that won't be very pleasant for your storage.
 
> As the article states, there are tradeoffs that each person must make between costs/convenience and security.

Fully agree.

> Are we OK to close this issue?

Yes, I only wanted to provide some insight in this kind of broad statement.

If a hypothetical adversary has unlimited funds and time: encryption and physical destruction.
If dismantling your drive is not an option and no firmware back-doors are available, then overwriting free space will be sufficient.

**Comment by az0** [comment]
> 
> > Are we OK to close this issue?
> 
> Yes, I only wanted to provide some insight in this kind of broad statement.

OK, I am closing
