### ISSUE TITLE
Program:Win32/Wacapew.C!ml Detected with Micrososft Defender Antivirus

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#971]
[build 4.0.1.1664](https://ci.appveyor.com/project/az0/bleachbit/builds/33732268/artifacts)
https://www.virustotal.com/gui/file/11c5b519f40d152c7bbd5f5a3e4a01c1813e514e0447f2e7ca944943b8e3f435/detection
![pup](https://user-images.githubusercontent.com/44164186/86857979-5fb65b00-c0c8-11ea-941f-dfeadd890ab8.png)

**Comment by az0** [comment]
I submitted the Microsoft false positive at https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by az0** [comment]
I reported it to Avast at https://www.avast.com/en-us/false-positive-file-form.php . I think this also covers AVG

**Comment by az0** [comment]
I reported to eGambit at https://tehtris.com/en/false-positive-negative-requests/

I reported to SecureAge APEX at https://www.secureaplus.com/features/antivirus/report-false-positive/

I reported to AegisLab at https://www.aegislab.com/reportfp/	

I reported to Fortinet at https://fortiguard.com/faq/classificationdispute (wow, it asks so many questions)

I think some antivirus vendors share data with each other, so I am hopeful once they process these requests, this effort will cover most of the problem. Because the scope is so wide (12 false positives), I am not going to track each one. I'll just close the ticket for now. If the issue persists later, then we can revisit it then.

**Comment by az0** [comment]
Fortinet quickly replied
>We have noted a False Positive detection on the file "_ssl.pyd" with MD5: 68475ff55e4a45cd7fbf32bf4b96387b.
                     
>The sample appears to be a SSL component.

>The signature "W32/PossibleThreat" will be disabled, and changes will be reflected in the next Virus Signature update. 

Avast replied
>Our virus specialists have been working on this problem and the provided file has been whitelisted.

Microsoft responded

>We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

>1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
>2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
>3. Run "MpCmdRun.exe -SignatureUpdate"

> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

VirusTotal is already down to 10 detections

**Comment by ediowar** [comment]
The file "_ssl.pyd" contained in the [build 4.0.1.1675](https://ci.bleachbit.org/dl/4.0.1.1675-master/BleachBit-4.0.1.1675-portable.zip) has only [2]( https://www.virustotal.com/gui/file/f871245278c31fde8917b724ae46c1087324ab1a46be09197f39ccac2c351d6c/detection) false positives. Why did you need to replace it from the [build 4.0.1.1664](https://ci.appveyor.com/project/az0/bleachbit/builds/33732268/artifacts) in the [build 4.0.1.1678](https://ci.bleachbit.org/dl/4.0.1.1678-master/BleachBit-4.0.1.1678-portable.zip)?

**Comment by ediowar** [comment]
The file "_ssl.pyd" contained in the [build 4.0.1.1675](https://ci.bleachbit.org/dl/4.0.1.1675-master/BleachBit-4.0.1.1675-portable.zip) has only [2]( https://www.virustotal.com/gui/file/f871245278c31fde8917b724ae46c1087324ab1a46be09197f39ccac2c351d6c/detection) false positives. Why did you need to replace it in the [build 4.0.1.1678](https://ci.bleachbit.org/dl/4.0.1.1678-master/BleachBit-4.0.1.1678-portable.zip) with another file from the [build 4.0.1.1664](https://ci.appveyor.com/project/az0/bleachbit/builds/33732268/artifacts) ?

**Comment by ediowar** [comment]
The file "_ssl.pyd" contained in the [build 4.0.1.1675](https://ci.bleachbit.org/dl/4.0.1.1675-master/BleachBit-4.0.1.1675-portable.zip) has only [2]( https://www.virustotal.com/gui/file/f871245278c31fde8917b724ae46c1087324ab1a46be09197f39ccac2c351d6c/detection) false positives. Why did you need to replace it in the [build 4.0.1.1678](https://ci.bleachbit.org/dl/4.0.1.1678-master/BleachBit-4.0.1.1678-portable.zip) with another  from the [build 4.0.1.1664](https://ci.appveyor.com/project/az0/bleachbit/builds/33732268/artifacts)?

**Comment by ediowar** [comment]
Compare
[BleachBit-4.0.1.1664-portable.zip](https://www.virustotal.com/gui/file/7cad02a9d25fdb6c8fab9f053646f05e568fffc144770cc82df2538ee8d4d34a/detection)
[BleachBit-4.0.1.1675-portable.zip](https://www.virustotal.com/gui/file/47a848cc4a99a2bfc9399d54ea554d0387aa8374709574061d9f9e689dae61c7/detection)
[BleachBit-4.0.1.1678-portable.zip](https://www.virustotal.com/gui/file/8197ee3326be55dfe763c2305777cb0e3245089d6e7fa132dfb8fe9634d0642e/detection)

**Comment by az0** [comment]
> Why did you need to replace it in the build 4.0.1.1678 with another from the build 4.0.1.1664?

> Compare VT detections
> [BleachBit-4.0.1.1664-portable.zip](https://www.virustotal.com/gui/file/7cad02a9d25fdb6c8fab9f053646f05e568fffc144770cc82df2538ee8d4d34a/detection)
> [BleachBit-4.0.1.1675-portable.zip](https://www.virustotal.com/gui/file/47a848cc4a99a2bfc9399d54ea554d0387aa8374709574061d9f9e689dae61c7/detection)
> [BleachBit-4.0.1.1678-portable.zip](https://www.virustotal.com/gui/file/8197ee3326be55dfe763c2305777cb0e3245089d6e7fa132dfb8fe9634d0642e/detection)

Later I will take a closer look, but I expect the `_ssl.pyd` file should be the same because all these versions come from Python 3.4.4 compressed with UPX, unless UPX compression is non-deterministic.

**Comment by az0** [comment]
I downloaded the portable versions of the three builds and compared the md5 hashes. They are different.

```
68475ff55e4a45cd7fbf32bf4b96387b  ./1664/BleachBit-Portable/_ssl.pyd
68475ff55e4a45cd7fbf32bf4b96387b  ./1678/BleachBit-Portable/_ssl.pyd
add26db10c42d5e2a7e1a54718637a66  ./1675/BleachBit-Portable/_ssl.pyd
```

After decompression (`upx -d`), I compared the files

```
$ cmp -l ./1664/BleachBit-Portable/_ssl.pyd ./1675/BleachBit-Portable/_ssl.pyd 
    137   0 162
    138   0 141
    139   0 155
    140   0  40
```

There is only a tiny difference, so I would hope that virus scanners would treat them the same.

As another test, I decompressed `_ssl.pyd` and recompressed it 100 times as follows, and it always had the same hash, so UPX is deterministic. (In other words, UPX is not causing the difference.)

```
for i in $(seq 1 100)
do
  cp _ssl.pyd ssl$i
  upx --best --crp-ms=999999 --nrv2e -qqq ssl$i
  md5sum ssl$i
done
```

Maybe py2exe is causing the differences with something like a date stamp. In any case, it was not intentional, and I do not see any obvious way to avoid it.

For beta and final builds, it is a manageable problem by whitelisting any false positives with the antivirus vendors.
