### ISSUE TITLE
GTK crash running bleachbit as sudo on Fedora linux

### ISSUE THREAD

**Issue by sjclondonukgreat** [bleachbit/bleachbit#981]
Running:    
`sudo bleachbit`
on Fedora 32, BleachBit version 4.0.0 crashes:

(non sudo bleachbit from command line works fine)...

No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused

(bleachbit:3891): Gdk-CRITICAL **: 09:12:12.381: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
No protocol specified
Unable to init server: Could not connect: Connection refused

(bleachbit:3891): Gtk-WARNING **: 09:12:12.392: cannot open display: :0

**Comment by az0** [comment]
I tried `sudo bleachbit` on Fedora 31 with BleachBit 3.9.0 (that's the system I had handy), and it worked fine. Have you tried searching the [web for your error message](https://duckduckgo.com/?q=No+protocol+specified+Unable+to+init+server%3A+Could+not+connect%3A+Connection+refused+sudo+fedora&)? This issue is not specific to BleachBit.

Have you also tried other applications such as `sudo gedit`?

Let me know how it goes. If you need more help, please let me know whether your windowing system is X or Wayland.

**Comment by sjclondonukgreat** [comment]
Thanks.

sudo works fine will other applications on my system

My system:

Fedora 32 - KDE spin. KDE plasma 5.18.5. 64bit. X windows.

I used to use 3.9.0 on linux mint (ubuntu) - that worked fine as sudo. I changed to F32. bleachbit 4.0.0 works, but sudo errors. I wonder if anyone else has experienced this?

**Comment by ediowar** [comment]
Seems to be a dup of https://github.com/bleachbit/bleachbit/issues/919 , https://github.com/bleachbit/bleachbit/issues/922

**Comment by abitrolly** [comment]
Can not reproduce on Fedora 33 with GNOME and X11 or Wayland.  @sjclondonukgreat can you test if the issue still repeats on your system, and paste the output of `bleachbit --sysinfo`?

**Comment by sjclondonukgreat** [comment]
I have F33 now and KDE with X11. It seems to work now, so the issue must have resolved itself. I use 4.0.0.

**Comment by abitrolly** [comment]
@sjclondonukgreat thanks for the update. That could have been an issue with GTK not specific to BleachBit that got fixed. Just a guess - I am not monitoring GTK development closely to find some prooflinks.
